# This file was automatically generated by Vpl
# utilization reports
report_utilization_impl true "DPUCZDX8G digitcaps_accel" "placed" "" $input_dir $vivado_output_dir
collect_compute_unit_utilization ""
