-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity digitcaps_accel_digitcaps_accel_Pipeline_VITIS_LOOP_286_1_VITIS_LOOP_289_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    squashed_v_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    squashed_v_ce0 : OUT STD_LOGIC;
    squashed_v_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    squashed_v_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    squashed_v_ce1 : OUT STD_LOGIC;
    squashed_v_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    squashed_v_address2 : OUT STD_LOGIC_VECTOR (7 downto 0);
    squashed_v_ce2 : OUT STD_LOGIC;
    squashed_v_q2 : IN STD_LOGIC_VECTOR (31 downto 0);
    squashed_v_address3 : OUT STD_LOGIC_VECTOR (7 downto 0);
    squashed_v_ce3 : OUT STD_LOGIC;
    squashed_v_q3 : IN STD_LOGIC_VECTOR (31 downto 0);
    squashed_v_address4 : OUT STD_LOGIC_VECTOR (7 downto 0);
    squashed_v_ce4 : OUT STD_LOGIC;
    squashed_v_q4 : IN STD_LOGIC_VECTOR (31 downto 0);
    squashed_v_address5 : OUT STD_LOGIC_VECTOR (7 downto 0);
    squashed_v_ce5 : OUT STD_LOGIC;
    squashed_v_q5 : IN STD_LOGIC_VECTOR (31 downto 0);
    squashed_v_address6 : OUT STD_LOGIC_VECTOR (7 downto 0);
    squashed_v_ce6 : OUT STD_LOGIC;
    squashed_v_q6 : IN STD_LOGIC_VECTOR (31 downto 0);
    squashed_v_address7 : OUT STD_LOGIC_VECTOR (7 downto 0);
    squashed_v_ce7 : OUT STD_LOGIC;
    squashed_v_q7 : IN STD_LOGIC_VECTOR (31 downto 0);
    squashed_v_address8 : OUT STD_LOGIC_VECTOR (7 downto 0);
    squashed_v_ce8 : OUT STD_LOGIC;
    squashed_v_q8 : IN STD_LOGIC_VECTOR (31 downto 0);
    squashed_v_address9 : OUT STD_LOGIC_VECTOR (7 downto 0);
    squashed_v_ce9 : OUT STD_LOGIC;
    squashed_v_q9 : IN STD_LOGIC_VECTOR (31 downto 0);
    squashed_v_address10 : OUT STD_LOGIC_VECTOR (7 downto 0);
    squashed_v_ce10 : OUT STD_LOGIC;
    squashed_v_q10 : IN STD_LOGIC_VECTOR (31 downto 0);
    squashed_v_address11 : OUT STD_LOGIC_VECTOR (7 downto 0);
    squashed_v_ce11 : OUT STD_LOGIC;
    squashed_v_q11 : IN STD_LOGIC_VECTOR (31 downto 0);
    squashed_v_address12 : OUT STD_LOGIC_VECTOR (7 downto 0);
    squashed_v_ce12 : OUT STD_LOGIC;
    squashed_v_q12 : IN STD_LOGIC_VECTOR (31 downto 0);
    squashed_v_address13 : OUT STD_LOGIC_VECTOR (7 downto 0);
    squashed_v_ce13 : OUT STD_LOGIC;
    squashed_v_q13 : IN STD_LOGIC_VECTOR (31 downto 0);
    squashed_v_address14 : OUT STD_LOGIC_VECTOR (7 downto 0);
    squashed_v_ce14 : OUT STD_LOGIC;
    squashed_v_q14 : IN STD_LOGIC_VECTOR (31 downto 0);
    squashed_v_address15 : OUT STD_LOGIC_VECTOR (7 downto 0);
    squashed_v_ce15 : OUT STD_LOGIC;
    squashed_v_q15 : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_input_u_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    weighted_input_u_ce0 : OUT STD_LOGIC;
    weighted_input_u_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_input_u_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    weighted_input_u_ce1 : OUT STD_LOGIC;
    weighted_input_u_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_input_u_1_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    weighted_input_u_1_ce0 : OUT STD_LOGIC;
    weighted_input_u_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_input_u_1_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    weighted_input_u_1_ce1 : OUT STD_LOGIC;
    weighted_input_u_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_input_u_2_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    weighted_input_u_2_ce0 : OUT STD_LOGIC;
    weighted_input_u_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_input_u_2_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    weighted_input_u_2_ce1 : OUT STD_LOGIC;
    weighted_input_u_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_input_u_3_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    weighted_input_u_3_ce0 : OUT STD_LOGIC;
    weighted_input_u_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_input_u_3_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    weighted_input_u_3_ce1 : OUT STD_LOGIC;
    weighted_input_u_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_input_u_4_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    weighted_input_u_4_ce0 : OUT STD_LOGIC;
    weighted_input_u_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_input_u_4_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    weighted_input_u_4_ce1 : OUT STD_LOGIC;
    weighted_input_u_4_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_input_u_5_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    weighted_input_u_5_ce0 : OUT STD_LOGIC;
    weighted_input_u_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_input_u_5_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    weighted_input_u_5_ce1 : OUT STD_LOGIC;
    weighted_input_u_5_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_input_u_6_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    weighted_input_u_6_ce0 : OUT STD_LOGIC;
    weighted_input_u_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_input_u_6_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    weighted_input_u_6_ce1 : OUT STD_LOGIC;
    weighted_input_u_6_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_input_u_7_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    weighted_input_u_7_ce0 : OUT STD_LOGIC;
    weighted_input_u_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    weighted_input_u_7_address1 : OUT STD_LOGIC_VECTOR (14 downto 0);
    weighted_input_u_7_ce1 : OUT STD_LOGIC;
    weighted_input_u_7_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_agreement_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    output_agreement_ce0 : OUT STD_LOGIC;
    output_agreement_we0 : OUT STD_LOGIC;
    output_agreement_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_531_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_531_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_531_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_531_p_ce : OUT STD_LOGIC;
    grp_fu_535_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_535_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_535_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_535_p_ce : OUT STD_LOGIC;
    grp_fu_539_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_539_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_539_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_539_p_ce : OUT STD_LOGIC;
    grp_fu_543_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_543_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_543_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_543_p_ce : OUT STD_LOGIC;
    grp_fu_547_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_547_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_547_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_547_p_ce : OUT STD_LOGIC;
    grp_fu_551_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_551_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_551_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_551_p_ce : OUT STD_LOGIC;
    grp_fu_555_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_555_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_555_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_555_p_ce : OUT STD_LOGIC;
    grp_fu_559_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_559_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_559_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_559_p_ce : OUT STD_LOGIC;
    grp_fu_563_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_563_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_563_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_563_p_ce : OUT STD_LOGIC;
    grp_fu_567_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_567_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_567_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_567_p_ce : OUT STD_LOGIC;
    grp_fu_571_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_571_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_571_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_571_p_ce : OUT STD_LOGIC;
    grp_fu_575_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_575_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_575_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_575_p_ce : OUT STD_LOGIC;
    grp_fu_579_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_579_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_579_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_579_p_ce : OUT STD_LOGIC;
    grp_fu_583_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_583_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_583_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_583_p_ce : OUT STD_LOGIC;
    grp_fu_587_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_587_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_587_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_587_p_ce : OUT STD_LOGIC;
    grp_fu_591_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_591_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_591_p_dout0 : IN STD_LOGIC_VECTOR (47 downto 0);
    grp_fu_591_p_ce : OUT STD_LOGIC );
end;


architecture behav of digitcaps_accel_digitcaps_accel_Pipeline_VITIS_LOOP_286_1_VITIS_LOOP_289_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv14_2D00 : STD_LOGIC_VECTOR (13 downto 0) := "10110100000000";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv11_480 : STD_LOGIC_VECTOR (10 downto 0) := "10010000000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln286_fu_630_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln286_fu_659_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln286_reg_1497 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln286_reg_1497_pp0_iter2_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln286_reg_1497_pp0_iter3_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln286_reg_1497_pp0_iter4_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln286_reg_1497_pp0_iter5_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln286_reg_1497_pp0_iter6_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln286_reg_1497_pp0_iter7_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln286_reg_1497_pp0_iter8_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln286_1_fu_673_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln286_1_reg_1503 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln286_1_reg_1503_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln286_1_reg_1503_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln286_1_reg_1503_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln286_1_reg_1503_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln286_1_reg_1503_pp0_iter6_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln286_1_reg_1503_pp0_iter7_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln286_1_reg_1503_pp0_iter8_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln294_fu_774_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln294_reg_1542 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln294_reg_1542_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln294_reg_1542_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_39_reg_1566 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_39_reg_1566_pp0_iter3_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_39_reg_1566_pp0_iter4_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal squashed_v_load_reg_1571 : STD_LOGIC_VECTOR (31 downto 0);
    signal squashed_v_load_1_reg_1576 : STD_LOGIC_VECTOR (31 downto 0);
    signal squashed_v_load_2_reg_1581 : STD_LOGIC_VECTOR (31 downto 0);
    signal weighted_input_u_load_reg_1596 : STD_LOGIC_VECTOR (31 downto 0);
    signal weighted_input_u_1_load_reg_1601 : STD_LOGIC_VECTOR (31 downto 0);
    signal weighted_input_u_2_load_reg_1606 : STD_LOGIC_VECTOR (31 downto 0);
    signal squashed_v_load_1_cast_fu_815_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal squashed_v_load_2_cast_fu_819_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal squashed_v_load_3_cast_fu_823_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal squashed_v_load_3_reg_1636 : STD_LOGIC_VECTOR (31 downto 0);
    signal squashed_v_load_4_reg_1641 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln294_fu_851_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln294_1_fu_855_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln294_2_fu_859_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal weighted_input_u_3_load_reg_1671 : STD_LOGIC_VECTOR (31 downto 0);
    signal weighted_input_u_4_load_reg_1676 : STD_LOGIC_VECTOR (31 downto 0);
    signal squashed_v_load_4_cast_fu_863_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal squashed_v_load_5_cast_fu_867_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal squashed_v_load_5_reg_1701 : STD_LOGIC_VECTOR (31 downto 0);
    signal squashed_v_load_6_reg_1706 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln294_1_reg_1721 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_32_reg_1726 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln294_2_reg_1731 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln294_3_fu_905_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln294_4_fu_909_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal weighted_input_u_5_load_reg_1746 : STD_LOGIC_VECTOR (31 downto 0);
    signal weighted_input_u_6_load_reg_1751 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln294_1_fu_920_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln294_1_reg_1761 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln294_1_reg_1761_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln294_1_reg_1761_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln294_1_reg_1761_pp0_iter8_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal squashed_v_load_6_cast_fu_925_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal squashed_v_load_7_cast_fu_929_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal squashed_v_load_7_reg_1787 : STD_LOGIC_VECTOR (31 downto 0);
    signal squashed_v_load_8_reg_1792 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln294_3_reg_1807 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_34_reg_1812 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln294_4_reg_1817 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln294_5_fu_1002_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln294_6_fu_1006_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal weighted_input_u_7_load_reg_1832 : STD_LOGIC_VECTOR (31 downto 0);
    signal weighted_input_u_load_1_reg_1837 : STD_LOGIC_VECTOR (31 downto 0);
    signal squashed_v_load_8_cast_fu_1010_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal squashed_v_load_9_cast_fu_1014_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal squashed_v_load_9_reg_1862 : STD_LOGIC_VECTOR (31 downto 0);
    signal squashed_v_load_10_reg_1867 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln294_5_reg_1882 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_36_reg_1887 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln294_6_reg_1892 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln294_7_fu_1087_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln294_8_fu_1091_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal weighted_input_u_1_load_1_reg_1907 : STD_LOGIC_VECTOR (31 downto 0);
    signal weighted_input_u_2_load_1_reg_1912 : STD_LOGIC_VECTOR (31 downto 0);
    signal squashed_v_load_10_cast_fu_1095_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal squashed_v_load_11_cast_fu_1099_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal squashed_v_load_11_reg_1937 : STD_LOGIC_VECTOR (31 downto 0);
    signal squashed_v_load_12_reg_1942 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln294_7_reg_1957 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_38_reg_1962 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln294_8_reg_1967 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln294_9_fu_1172_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln294_10_fu_1176_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal weighted_input_u_3_load_1_reg_1982 : STD_LOGIC_VECTOR (31 downto 0);
    signal weighted_input_u_4_load_1_reg_1987 : STD_LOGIC_VECTOR (31 downto 0);
    signal squashed_v_load_12_cast_fu_1204_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal squashed_v_load_13_cast_fu_1208_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal squashed_v_load_13_reg_2012 : STD_LOGIC_VECTOR (31 downto 0);
    signal squashed_v_load_14_reg_2017 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln294_9_reg_2027 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_41_reg_2032 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln294_10_reg_2037 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln294_11_fu_1272_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln294_12_fu_1276_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal weighted_input_u_5_load_1_reg_2052 : STD_LOGIC_VECTOR (31 downto 0);
    signal weighted_input_u_6_load_1_reg_2057 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln296_fu_1280_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln296_reg_2067 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln296_reg_2067_pp0_iter10_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln296_reg_2067_pp0_iter11_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln296_reg_2067_pp0_iter12_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal squashed_v_load_14_cast_fu_1286_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal squashed_v_load_15_cast_fu_1290_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal squashed_v_load_15_reg_2082 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln294_11_reg_2087 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_43_reg_2092 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln294_12_reg_2097 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln294_13_fu_1339_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln294_14_fu_1343_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal weighted_input_u_7_load_1_reg_2112 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln289_fu_1347_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal mul_ln294_13_reg_2122 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_45_reg_2127 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln294_14_reg_2132 : STD_LOGIC_VECTOR (47 downto 0);
    signal sext_ln294_15_fu_1396_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal mul_ln294_15_reg_2142 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_47_reg_2147 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_cast15_fu_704_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal p_cast16_fu_740_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast17_fu_752_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast18_fu_798_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast19_fu_810_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast20_fu_834_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast21_fu_846_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast22_fu_878_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast23_fu_890_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast24_fu_940_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast25_fu_952_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast26_fu_1025_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast27_fu_1037_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast28_fu_1110_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast29_fu_1122_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast30_fu_1219_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln296_fu_1468_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_130 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln289_fu_681_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_1_fu_134 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal indvar_flatten20_fu_138 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    signal add_ln286_fu_636_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_sig_allocacmp_indvar_flatten20_load : STD_LOGIC_VECTOR (13 downto 0);
    signal squashed_v_ce15_local : STD_LOGIC;
    signal squashed_v_ce14_local : STD_LOGIC;
    signal squashed_v_ce13_local : STD_LOGIC;
    signal squashed_v_ce12_local : STD_LOGIC;
    signal squashed_v_ce11_local : STD_LOGIC;
    signal squashed_v_ce10_local : STD_LOGIC;
    signal squashed_v_ce9_local : STD_LOGIC;
    signal squashed_v_ce8_local : STD_LOGIC;
    signal squashed_v_ce7_local : STD_LOGIC;
    signal squashed_v_ce6_local : STD_LOGIC;
    signal squashed_v_ce5_local : STD_LOGIC;
    signal squashed_v_ce4_local : STD_LOGIC;
    signal squashed_v_ce3_local : STD_LOGIC;
    signal squashed_v_ce2_local : STD_LOGIC;
    signal squashed_v_ce1_local : STD_LOGIC;
    signal squashed_v_ce0_local : STD_LOGIC;
    signal weighted_input_u_ce1_local : STD_LOGIC;
    signal weighted_input_u_ce0_local : STD_LOGIC;
    signal weighted_input_u_1_ce1_local : STD_LOGIC;
    signal weighted_input_u_1_ce0_local : STD_LOGIC;
    signal weighted_input_u_2_ce1_local : STD_LOGIC;
    signal weighted_input_u_2_ce0_local : STD_LOGIC;
    signal weighted_input_u_3_ce1_local : STD_LOGIC;
    signal weighted_input_u_3_ce0_local : STD_LOGIC;
    signal weighted_input_u_4_ce1_local : STD_LOGIC;
    signal weighted_input_u_4_ce0_local : STD_LOGIC;
    signal weighted_input_u_5_ce1_local : STD_LOGIC;
    signal weighted_input_u_5_ce0_local : STD_LOGIC;
    signal weighted_input_u_6_ce1_local : STD_LOGIC;
    signal weighted_input_u_6_ce0_local : STD_LOGIC;
    signal weighted_input_u_7_ce1_local : STD_LOGIC;
    signal weighted_input_u_7_ce0_local : STD_LOGIC;
    signal output_agreement_we0_local : STD_LOGIC;
    signal output_agreement_ce0_local : STD_LOGIC;
    signal icmp_ln289_fu_653_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln286_1_fu_667_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_16_fu_697_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_115_fu_716_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_shl_fu_709_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_shl31_fu_723_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_17_fu_733_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_18_fu_745_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_udiv_fu_757_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_udiv2527_cast_fu_764_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_udiv2428_fu_727_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_udiv26_fu_768_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_19_fu_791_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_20_fu_803_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_21_fu_827_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_22_fu_839_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_23_fu_871_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_24_fu_883_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln_fu_913_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_25_fu_933_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_26_fu_945_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln2_fu_957_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln294_fu_964_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_33_fu_969_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln294_1_fu_979_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln294_1_fu_987_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_27_fu_1018_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_28_fu_1030_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln294_2_fu_1042_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln294_2_fu_1049_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_35_fu_1054_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln294_3_fu_1064_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln294_3_fu_1072_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_29_fu_1103_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_30_fu_1115_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln294_4_fu_1127_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln294_4_fu_1134_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_37_fu_1139_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln294_5_fu_1149_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln294_5_fu_1157_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_fu_1187_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl1_fu_1180_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_shl33_fu_1194_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_31_fu_1212_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln294_6_fu_1227_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln294_6_fu_1234_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_40_fu_1239_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln294_7_fu_1249_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln294_7_fu_1257_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal zext_ln289_fu_1224_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal empty_fu_1198_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln294_8_fu_1294_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln294_8_fu_1301_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_42_fu_1306_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln294_9_fu_1316_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln294_9_fu_1324_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal shl_ln294_s_fu_1351_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln294_10_fu_1358_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_44_fu_1363_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln294_10_fu_1373_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln294_11_fu_1381_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal shl_ln294_11_fu_1400_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln294_12_fu_1407_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_46_fu_1412_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln294_12_fu_1422_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln294_13_fu_1430_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal shl_ln294_13_fu_1445_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal add_ln294_14_fu_1452_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component digitcaps_accel_mul_32s_32s_48_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component digitcaps_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component digitcaps_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter12_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    i_1_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_1_fu_134 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    i_1_fu_134 <= select_ln286_1_fu_673_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten20_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln286_fu_630_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten20_fu_138 <= add_ln286_fu_636_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten20_fu_138 <= ap_const_lv14_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_130 <= ap_const_lv11_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    j_fu_130 <= add_ln289_fu_681_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln296_reg_2067 <= add_ln296_fu_1280_p2;
                add_ln296_reg_2067_pp0_iter10_reg <= add_ln296_reg_2067;
                add_ln296_reg_2067_pp0_iter11_reg <= add_ln296_reg_2067_pp0_iter10_reg;
                add_ln296_reg_2067_pp0_iter12_reg <= add_ln296_reg_2067_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                mul_ln294_10_reg_2037 <= grp_fu_571_p_dout0;
                mul_ln294_11_reg_2087 <= grp_fu_575_p_dout0;
                mul_ln294_12_reg_2097 <= grp_fu_579_p_dout0;
                mul_ln294_13_reg_2122 <= grp_fu_583_p_dout0;
                mul_ln294_14_reg_2132 <= grp_fu_587_p_dout0;
                mul_ln294_15_reg_2142 <= grp_fu_591_p_dout0;
                mul_ln294_1_reg_1721 <= grp_fu_535_p_dout0;
                mul_ln294_2_reg_1731 <= grp_fu_539_p_dout0;
                mul_ln294_3_reg_1807 <= grp_fu_543_p_dout0;
                mul_ln294_4_reg_1817 <= grp_fu_547_p_dout0;
                mul_ln294_5_reg_1882 <= grp_fu_551_p_dout0;
                mul_ln294_6_reg_1892 <= grp_fu_555_p_dout0;
                mul_ln294_7_reg_1957 <= grp_fu_559_p_dout0;
                mul_ln294_8_reg_1967 <= grp_fu_563_p_dout0;
                mul_ln294_9_reg_2027 <= grp_fu_567_p_dout0;
                select_ln286_1_reg_1503_pp0_iter2_reg <= select_ln286_1_reg_1503;
                select_ln286_1_reg_1503_pp0_iter3_reg <= select_ln286_1_reg_1503_pp0_iter2_reg;
                select_ln286_1_reg_1503_pp0_iter4_reg <= select_ln286_1_reg_1503_pp0_iter3_reg;
                select_ln286_1_reg_1503_pp0_iter5_reg <= select_ln286_1_reg_1503_pp0_iter4_reg;
                select_ln286_1_reg_1503_pp0_iter6_reg <= select_ln286_1_reg_1503_pp0_iter5_reg;
                select_ln286_1_reg_1503_pp0_iter7_reg <= select_ln286_1_reg_1503_pp0_iter6_reg;
                select_ln286_1_reg_1503_pp0_iter8_reg <= select_ln286_1_reg_1503_pp0_iter7_reg;
                select_ln286_reg_1497_pp0_iter2_reg <= select_ln286_reg_1497;
                select_ln286_reg_1497_pp0_iter3_reg <= select_ln286_reg_1497_pp0_iter2_reg;
                select_ln286_reg_1497_pp0_iter4_reg <= select_ln286_reg_1497_pp0_iter3_reg;
                select_ln286_reg_1497_pp0_iter5_reg <= select_ln286_reg_1497_pp0_iter4_reg;
                select_ln286_reg_1497_pp0_iter6_reg <= select_ln286_reg_1497_pp0_iter5_reg;
                select_ln286_reg_1497_pp0_iter7_reg <= select_ln286_reg_1497_pp0_iter6_reg;
                select_ln286_reg_1497_pp0_iter8_reg <= select_ln286_reg_1497_pp0_iter7_reg;
                tmp_32_reg_1726 <= grp_fu_531_p_dout0(47 downto 16);
                tmp_34_reg_1812 <= add_ln294_1_fu_987_p2(47 downto 16);
                tmp_36_reg_1887 <= add_ln294_3_fu_1072_p2(47 downto 16);
                tmp_38_reg_1962 <= add_ln294_5_fu_1157_p2(47 downto 16);
                tmp_39_reg_1566 <= p_udiv26_fu_768_p2(14 downto 1);
                tmp_39_reg_1566_pp0_iter3_reg <= tmp_39_reg_1566;
                tmp_39_reg_1566_pp0_iter4_reg <= tmp_39_reg_1566_pp0_iter3_reg;
                tmp_41_reg_2032 <= add_ln294_7_fu_1257_p2(47 downto 16);
                tmp_43_reg_2092 <= add_ln294_9_fu_1324_p2(47 downto 16);
                tmp_45_reg_2127 <= add_ln294_11_fu_1381_p2(47 downto 16);
                tmp_47_reg_2147 <= add_ln294_13_fu_1430_p2(47 downto 16);
                    zext_ln294_1_reg_1761(14 downto 1) <= zext_ln294_1_fu_920_p1(14 downto 1);
                    zext_ln294_1_reg_1761_pp0_iter6_reg(14 downto 1) <= zext_ln294_1_reg_1761(14 downto 1);
                    zext_ln294_1_reg_1761_pp0_iter7_reg(14 downto 1) <= zext_ln294_1_reg_1761_pp0_iter6_reg(14 downto 1);
                    zext_ln294_1_reg_1761_pp0_iter8_reg(14 downto 1) <= zext_ln294_1_reg_1761_pp0_iter7_reg(14 downto 1);
                    zext_ln294_reg_1542(14 downto 1) <= zext_ln294_fu_774_p1(14 downto 1);
                    zext_ln294_reg_1542_pp0_iter3_reg(14 downto 1) <= zext_ln294_reg_1542(14 downto 1);
                    zext_ln294_reg_1542_pp0_iter4_reg(14 downto 1) <= zext_ln294_reg_1542_pp0_iter3_reg(14 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                select_ln286_1_reg_1503 <= select_ln286_1_fu_673_p3;
                select_ln286_reg_1497 <= select_ln286_fu_659_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then
                squashed_v_load_10_reg_1867 <= squashed_v_q5;
                squashed_v_load_9_reg_1862 <= squashed_v_q6;
                weighted_input_u_1_load_1_reg_1907 <= weighted_input_u_1_q0;
                weighted_input_u_2_load_1_reg_1912 <= weighted_input_u_2_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then
                squashed_v_load_11_reg_1937 <= squashed_v_q4;
                squashed_v_load_12_reg_1942 <= squashed_v_q3;
                weighted_input_u_3_load_1_reg_1982 <= weighted_input_u_3_q0;
                weighted_input_u_4_load_1_reg_1987 <= weighted_input_u_4_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then
                squashed_v_load_13_reg_2012 <= squashed_v_q2;
                squashed_v_load_14_reg_2017 <= squashed_v_q1;
                weighted_input_u_5_load_1_reg_2052 <= weighted_input_u_5_q0;
                weighted_input_u_6_load_1_reg_2057 <= weighted_input_u_6_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then
                squashed_v_load_15_reg_2082 <= squashed_v_q0;
                weighted_input_u_7_load_1_reg_2112 <= weighted_input_u_7_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                squashed_v_load_1_reg_1576 <= squashed_v_q14;
                squashed_v_load_2_reg_1581 <= squashed_v_q13;
                squashed_v_load_reg_1571 <= squashed_v_q15;
                weighted_input_u_1_load_reg_1601 <= weighted_input_u_1_q1;
                weighted_input_u_2_load_reg_1606 <= weighted_input_u_2_q1;
                weighted_input_u_load_reg_1596 <= weighted_input_u_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then
                squashed_v_load_3_reg_1636 <= squashed_v_q12;
                squashed_v_load_4_reg_1641 <= squashed_v_q11;
                weighted_input_u_3_load_reg_1671 <= weighted_input_u_3_q1;
                weighted_input_u_4_load_reg_1676 <= weighted_input_u_4_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then
                squashed_v_load_5_reg_1701 <= squashed_v_q10;
                squashed_v_load_6_reg_1706 <= squashed_v_q9;
                weighted_input_u_5_load_reg_1746 <= weighted_input_u_5_q1;
                weighted_input_u_6_load_reg_1751 <= weighted_input_u_6_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then
                squashed_v_load_7_reg_1787 <= squashed_v_q8;
                squashed_v_load_8_reg_1792 <= squashed_v_q7;
                weighted_input_u_7_load_reg_1832 <= weighted_input_u_7_q1;
                weighted_input_u_load_1_reg_1837 <= weighted_input_u_q0;
            end if;
        end if;
    end process;
    zext_ln294_reg_1542(0) <= '0';
    zext_ln294_reg_1542(63 downto 15) <= "0000000000000000000000000000000000000000000000000";
    zext_ln294_reg_1542_pp0_iter3_reg(0) <= '0';
    zext_ln294_reg_1542_pp0_iter3_reg(63 downto 15) <= "0000000000000000000000000000000000000000000000000";
    zext_ln294_reg_1542_pp0_iter4_reg(0) <= '0';
    zext_ln294_reg_1542_pp0_iter4_reg(63 downto 15) <= "0000000000000000000000000000000000000000000000000";
    zext_ln294_1_reg_1761(0) <= '1';
    zext_ln294_1_reg_1761(63 downto 15) <= "0000000000000000000000000000000000000000000000000";
    zext_ln294_1_reg_1761_pp0_iter6_reg(0) <= '1';
    zext_ln294_1_reg_1761_pp0_iter6_reg(63 downto 15) <= "0000000000000000000000000000000000000000000000000";
    zext_ln294_1_reg_1761_pp0_iter7_reg(0) <= '1';
    zext_ln294_1_reg_1761_pp0_iter7_reg(63 downto 15) <= "0000000000000000000000000000000000000000000000000";
    zext_ln294_1_reg_1761_pp0_iter8_reg(0) <= '1';
    zext_ln294_1_reg_1761_pp0_iter8_reg(63 downto 15) <= "0000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln286_1_fu_667_p2 <= std_logic_vector(unsigned(i_1_fu_134) + unsigned(ap_const_lv4_1));
    add_ln286_fu_636_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten20_load) + unsigned(ap_const_lv14_1));
    add_ln289_fu_681_p2 <= std_logic_vector(unsigned(select_ln286_fu_659_p3) + unsigned(ap_const_lv11_1));
    add_ln294_10_fu_1358_p2 <= std_logic_vector(unsigned(shl_ln294_s_fu_1351_p3) + unsigned(mul_ln294_11_reg_2087));
    add_ln294_11_fu_1381_p2 <= std_logic_vector(unsigned(shl_ln294_10_fu_1373_p3) + unsigned(mul_ln294_12_reg_2097));
    add_ln294_12_fu_1407_p2 <= std_logic_vector(unsigned(shl_ln294_11_fu_1400_p3) + unsigned(mul_ln294_13_reg_2122));
    add_ln294_13_fu_1430_p2 <= std_logic_vector(unsigned(shl_ln294_12_fu_1422_p3) + unsigned(mul_ln294_14_reg_2132));
    add_ln294_14_fu_1452_p2 <= std_logic_vector(unsigned(shl_ln294_13_fu_1445_p3) + unsigned(mul_ln294_15_reg_2142));
    add_ln294_1_fu_987_p2 <= std_logic_vector(unsigned(shl_ln294_1_fu_979_p3) + unsigned(mul_ln294_2_reg_1731));
    add_ln294_2_fu_1049_p2 <= std_logic_vector(unsigned(shl_ln294_2_fu_1042_p3) + unsigned(mul_ln294_3_reg_1807));
    add_ln294_3_fu_1072_p2 <= std_logic_vector(unsigned(shl_ln294_3_fu_1064_p3) + unsigned(mul_ln294_4_reg_1817));
    add_ln294_4_fu_1134_p2 <= std_logic_vector(unsigned(shl_ln294_4_fu_1127_p3) + unsigned(mul_ln294_5_reg_1882));
    add_ln294_5_fu_1157_p2 <= std_logic_vector(unsigned(shl_ln294_5_fu_1149_p3) + unsigned(mul_ln294_6_reg_1892));
    add_ln294_6_fu_1234_p2 <= std_logic_vector(unsigned(shl_ln294_6_fu_1227_p3) + unsigned(mul_ln294_7_reg_1957));
    add_ln294_7_fu_1257_p2 <= std_logic_vector(unsigned(shl_ln294_7_fu_1249_p3) + unsigned(mul_ln294_8_reg_1967));
    add_ln294_8_fu_1301_p2 <= std_logic_vector(unsigned(shl_ln294_8_fu_1294_p3) + unsigned(mul_ln294_9_reg_2027));
    add_ln294_9_fu_1324_p2 <= std_logic_vector(unsigned(shl_ln294_9_fu_1316_p3) + unsigned(mul_ln294_10_reg_2037));
    add_ln294_fu_964_p2 <= std_logic_vector(unsigned(shl_ln2_fu_957_p3) + unsigned(mul_ln294_1_reg_1721));
    add_ln296_fu_1280_p2 <= std_logic_vector(unsigned(zext_ln289_fu_1224_p1) + unsigned(empty_fu_1198_p2));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln286_fu_630_p2)
    begin
        if (((icmp_ln286_fu_630_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter12_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter12_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten20_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten20_fu_138)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten20_load <= ap_const_lv14_0;
        else 
            ap_sig_allocacmp_indvar_flatten20_load <= indvar_flatten20_fu_138;
        end if; 
    end process;

    empty_fu_1198_p2 <= std_logic_vector(unsigned(p_shl1_fu_1180_p3) + unsigned(p_shl33_fu_1194_p1));
    grp_fu_531_p_ce <= ap_const_logic_1;
    grp_fu_531_p_din0 <= sext_ln294_fu_851_p1(32 - 1 downto 0);
    grp_fu_531_p_din1 <= squashed_v_load_1_cast_fu_815_p1(32 - 1 downto 0);
    grp_fu_535_p_ce <= ap_const_logic_1;
    grp_fu_535_p_din0 <= sext_ln294_1_fu_855_p1(32 - 1 downto 0);
    grp_fu_535_p_din1 <= squashed_v_load_2_cast_fu_819_p1(32 - 1 downto 0);
    grp_fu_539_p_ce <= ap_const_logic_1;
    grp_fu_539_p_din0 <= sext_ln294_2_fu_859_p1(32 - 1 downto 0);
    grp_fu_539_p_din1 <= squashed_v_load_3_cast_fu_823_p1(32 - 1 downto 0);
    grp_fu_543_p_ce <= ap_const_logic_1;
    grp_fu_543_p_din0 <= sext_ln294_3_fu_905_p1(32 - 1 downto 0);
    grp_fu_543_p_din1 <= squashed_v_load_4_cast_fu_863_p1(32 - 1 downto 0);
    grp_fu_547_p_ce <= ap_const_logic_1;
    grp_fu_547_p_din0 <= sext_ln294_4_fu_909_p1(32 - 1 downto 0);
    grp_fu_547_p_din1 <= squashed_v_load_5_cast_fu_867_p1(32 - 1 downto 0);
    grp_fu_551_p_ce <= ap_const_logic_1;
    grp_fu_551_p_din0 <= sext_ln294_5_fu_1002_p1(32 - 1 downto 0);
    grp_fu_551_p_din1 <= squashed_v_load_6_cast_fu_925_p1(32 - 1 downto 0);
    grp_fu_555_p_ce <= ap_const_logic_1;
    grp_fu_555_p_din0 <= sext_ln294_6_fu_1006_p1(32 - 1 downto 0);
    grp_fu_555_p_din1 <= squashed_v_load_7_cast_fu_929_p1(32 - 1 downto 0);
    grp_fu_559_p_ce <= ap_const_logic_1;
    grp_fu_559_p_din0 <= sext_ln294_7_fu_1087_p1(32 - 1 downto 0);
    grp_fu_559_p_din1 <= squashed_v_load_8_cast_fu_1010_p1(32 - 1 downto 0);
    grp_fu_563_p_ce <= ap_const_logic_1;
    grp_fu_563_p_din0 <= sext_ln294_8_fu_1091_p1(32 - 1 downto 0);
    grp_fu_563_p_din1 <= squashed_v_load_9_cast_fu_1014_p1(32 - 1 downto 0);
    grp_fu_567_p_ce <= ap_const_logic_1;
    grp_fu_567_p_din0 <= sext_ln294_9_fu_1172_p1(32 - 1 downto 0);
    grp_fu_567_p_din1 <= squashed_v_load_10_cast_fu_1095_p1(32 - 1 downto 0);
    grp_fu_571_p_ce <= ap_const_logic_1;
    grp_fu_571_p_din0 <= sext_ln294_10_fu_1176_p1(32 - 1 downto 0);
    grp_fu_571_p_din1 <= squashed_v_load_11_cast_fu_1099_p1(32 - 1 downto 0);
    grp_fu_575_p_ce <= ap_const_logic_1;
    grp_fu_575_p_din0 <= sext_ln294_11_fu_1272_p1(32 - 1 downto 0);
    grp_fu_575_p_din1 <= squashed_v_load_12_cast_fu_1204_p1(32 - 1 downto 0);
    grp_fu_579_p_ce <= ap_const_logic_1;
    grp_fu_579_p_din0 <= sext_ln294_12_fu_1276_p1(32 - 1 downto 0);
    grp_fu_579_p_din1 <= squashed_v_load_13_cast_fu_1208_p1(32 - 1 downto 0);
    grp_fu_583_p_ce <= ap_const_logic_1;
    grp_fu_583_p_din0 <= sext_ln294_13_fu_1339_p1(32 - 1 downto 0);
    grp_fu_583_p_din1 <= squashed_v_load_14_cast_fu_1286_p1(32 - 1 downto 0);
    grp_fu_587_p_ce <= ap_const_logic_1;
    grp_fu_587_p_din0 <= sext_ln294_14_fu_1343_p1(32 - 1 downto 0);
    grp_fu_587_p_din1 <= squashed_v_load_15_cast_fu_1290_p1(32 - 1 downto 0);
    grp_fu_591_p_ce <= ap_const_logic_1;
    grp_fu_591_p_din0 <= sext_ln294_15_fu_1396_p1(32 - 1 downto 0);
    grp_fu_591_p_din1 <= sext_ln289_fu_1347_p1(32 - 1 downto 0);
    icmp_ln286_fu_630_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten20_load = ap_const_lv14_2D00) else "0";
    icmp_ln289_fu_653_p2 <= "1" when (j_fu_130 = ap_const_lv11_480) else "0";
    or_ln_fu_913_p3 <= (tmp_39_reg_1566_pp0_iter4_reg & ap_const_lv1_1);
    output_agreement_address0 <= zext_ln296_fu_1468_p1(14 - 1 downto 0);
    output_agreement_ce0 <= output_agreement_ce0_local;

    output_agreement_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            output_agreement_ce0_local <= ap_const_logic_1;
        else 
            output_agreement_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    output_agreement_d0 <= add_ln294_14_fu_1452_p2(47 downto 16);
    output_agreement_we0 <= output_agreement_we0_local;

    output_agreement_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            output_agreement_we0_local <= ap_const_logic_1;
        else 
            output_agreement_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_cast15_fu_704_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_16_fu_697_p3),64));
    p_cast16_fu_740_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_17_fu_733_p3),64));
    p_cast17_fu_752_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_18_fu_745_p3),64));
    p_cast18_fu_798_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_19_fu_791_p3),64));
    p_cast19_fu_810_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_20_fu_803_p3),64));
    p_cast20_fu_834_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_21_fu_827_p3),64));
    p_cast21_fu_846_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_22_fu_839_p3),64));
    p_cast22_fu_878_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_23_fu_871_p3),64));
    p_cast23_fu_890_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_24_fu_883_p3),64));
    p_cast24_fu_940_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_25_fu_933_p3),64));
    p_cast25_fu_952_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_26_fu_945_p3),64));
    p_cast26_fu_1025_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_27_fu_1018_p3),64));
    p_cast27_fu_1037_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_28_fu_1030_p3),64));
    p_cast28_fu_1110_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_29_fu_1103_p3),64));
    p_cast29_fu_1122_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_30_fu_1115_p3),64));
    p_cast30_fu_1219_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_31_fu_1212_p3),64));
    p_shl1_fu_1180_p3 <= (select_ln286_1_reg_1503_pp0_iter8_reg & ap_const_lv10_0);
    p_shl31_fu_723_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_115_fu_716_p3),15));
    p_shl33_fu_1194_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_1187_p3),14));
    p_shl_fu_709_p3 <= (select_ln286_1_reg_1503 & ap_const_lv11_0);
    p_udiv2428_fu_727_p2 <= std_logic_vector(unsigned(p_shl_fu_709_p3) + unsigned(p_shl31_fu_723_p1));
    p_udiv2527_cast_fu_764_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_udiv_fu_757_p3),15));
    p_udiv26_fu_768_p2 <= std_logic_vector(unsigned(p_udiv2527_cast_fu_764_p1) + unsigned(p_udiv2428_fu_727_p2));
    p_udiv_fu_757_p3 <= (select_ln286_reg_1497 & ap_const_lv1_0);
    select_ln286_1_fu_673_p3 <= 
        add_ln286_1_fu_667_p2 when (icmp_ln289_fu_653_p2(0) = '1') else 
        i_1_fu_134;
    select_ln286_fu_659_p3 <= 
        ap_const_lv11_0 when (icmp_ln289_fu_653_p2(0) = '1') else 
        j_fu_130;
        sext_ln289_fu_1347_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(squashed_v_load_15_reg_2082),48));

        sext_ln294_10_fu_1176_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(weighted_input_u_2_load_1_reg_1912),48));

        sext_ln294_11_fu_1272_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(weighted_input_u_3_load_1_reg_1982),48));

        sext_ln294_12_fu_1276_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(weighted_input_u_4_load_1_reg_1987),48));

        sext_ln294_13_fu_1339_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(weighted_input_u_5_load_1_reg_2052),48));

        sext_ln294_14_fu_1343_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(weighted_input_u_6_load_1_reg_2057),48));

        sext_ln294_15_fu_1396_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(weighted_input_u_7_load_1_reg_2112),48));

        sext_ln294_1_fu_855_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(weighted_input_u_1_load_reg_1601),48));

        sext_ln294_2_fu_859_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(weighted_input_u_2_load_reg_1606),48));

        sext_ln294_3_fu_905_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(weighted_input_u_3_load_reg_1671),48));

        sext_ln294_4_fu_909_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(weighted_input_u_4_load_reg_1676),48));

        sext_ln294_5_fu_1002_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(weighted_input_u_5_load_reg_1746),48));

        sext_ln294_6_fu_1006_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(weighted_input_u_6_load_reg_1751),48));

        sext_ln294_7_fu_1087_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(weighted_input_u_7_load_reg_1832),48));

        sext_ln294_8_fu_1091_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(weighted_input_u_load_1_reg_1837),48));

        sext_ln294_9_fu_1172_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(weighted_input_u_1_load_1_reg_1907),48));

        sext_ln294_fu_851_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(weighted_input_u_load_reg_1596),48));

    shl_ln294_10_fu_1373_p3 <= (tmp_44_fu_1363_p4 & ap_const_lv16_0);
    shl_ln294_11_fu_1400_p3 <= (tmp_45_reg_2127 & ap_const_lv16_0);
    shl_ln294_12_fu_1422_p3 <= (tmp_46_fu_1412_p4 & ap_const_lv16_0);
    shl_ln294_13_fu_1445_p3 <= (tmp_47_reg_2147 & ap_const_lv16_0);
    shl_ln294_1_fu_979_p3 <= (tmp_33_fu_969_p4 & ap_const_lv16_0);
    shl_ln294_2_fu_1042_p3 <= (tmp_34_reg_1812 & ap_const_lv16_0);
    shl_ln294_3_fu_1064_p3 <= (tmp_35_fu_1054_p4 & ap_const_lv16_0);
    shl_ln294_4_fu_1127_p3 <= (tmp_36_reg_1887 & ap_const_lv16_0);
    shl_ln294_5_fu_1149_p3 <= (tmp_37_fu_1139_p4 & ap_const_lv16_0);
    shl_ln294_6_fu_1227_p3 <= (tmp_38_reg_1962 & ap_const_lv16_0);
    shl_ln294_7_fu_1249_p3 <= (tmp_40_fu_1239_p4 & ap_const_lv16_0);
    shl_ln294_8_fu_1294_p3 <= (tmp_41_reg_2032 & ap_const_lv16_0);
    shl_ln294_9_fu_1316_p3 <= (tmp_42_fu_1306_p4 & ap_const_lv16_0);
    shl_ln294_s_fu_1351_p3 <= (tmp_43_reg_2092 & ap_const_lv16_0);
    shl_ln2_fu_957_p3 <= (tmp_32_reg_1726 & ap_const_lv16_0);
    squashed_v_address0 <= p_cast30_fu_1219_p1(8 - 1 downto 0);
    squashed_v_address1 <= p_cast29_fu_1122_p1(8 - 1 downto 0);
    squashed_v_address10 <= p_cast20_fu_834_p1(8 - 1 downto 0);
    squashed_v_address11 <= p_cast19_fu_810_p1(8 - 1 downto 0);
    squashed_v_address12 <= p_cast18_fu_798_p1(8 - 1 downto 0);
    squashed_v_address13 <= p_cast17_fu_752_p1(8 - 1 downto 0);
    squashed_v_address14 <= p_cast16_fu_740_p1(8 - 1 downto 0);
    squashed_v_address15 <= p_cast15_fu_704_p1(8 - 1 downto 0);
    squashed_v_address2 <= p_cast28_fu_1110_p1(8 - 1 downto 0);
    squashed_v_address3 <= p_cast27_fu_1037_p1(8 - 1 downto 0);
    squashed_v_address4 <= p_cast26_fu_1025_p1(8 - 1 downto 0);
    squashed_v_address5 <= p_cast25_fu_952_p1(8 - 1 downto 0);
    squashed_v_address6 <= p_cast24_fu_940_p1(8 - 1 downto 0);
    squashed_v_address7 <= p_cast23_fu_890_p1(8 - 1 downto 0);
    squashed_v_address8 <= p_cast22_fu_878_p1(8 - 1 downto 0);
    squashed_v_address9 <= p_cast21_fu_846_p1(8 - 1 downto 0);
    squashed_v_ce0 <= squashed_v_ce0_local;

    squashed_v_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            squashed_v_ce0_local <= ap_const_logic_1;
        else 
            squashed_v_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    squashed_v_ce1 <= squashed_v_ce1_local;
    squashed_v_ce10 <= squashed_v_ce10_local;

    squashed_v_ce10_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            squashed_v_ce10_local <= ap_const_logic_1;
        else 
            squashed_v_ce10_local <= ap_const_logic_0;
        end if; 
    end process;

    squashed_v_ce11 <= squashed_v_ce11_local;

    squashed_v_ce11_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            squashed_v_ce11_local <= ap_const_logic_1;
        else 
            squashed_v_ce11_local <= ap_const_logic_0;
        end if; 
    end process;

    squashed_v_ce12 <= squashed_v_ce12_local;

    squashed_v_ce12_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            squashed_v_ce12_local <= ap_const_logic_1;
        else 
            squashed_v_ce12_local <= ap_const_logic_0;
        end if; 
    end process;

    squashed_v_ce13 <= squashed_v_ce13_local;

    squashed_v_ce13_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            squashed_v_ce13_local <= ap_const_logic_1;
        else 
            squashed_v_ce13_local <= ap_const_logic_0;
        end if; 
    end process;

    squashed_v_ce14 <= squashed_v_ce14_local;

    squashed_v_ce14_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            squashed_v_ce14_local <= ap_const_logic_1;
        else 
            squashed_v_ce14_local <= ap_const_logic_0;
        end if; 
    end process;

    squashed_v_ce15 <= squashed_v_ce15_local;

    squashed_v_ce15_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            squashed_v_ce15_local <= ap_const_logic_1;
        else 
            squashed_v_ce15_local <= ap_const_logic_0;
        end if; 
    end process;


    squashed_v_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            squashed_v_ce1_local <= ap_const_logic_1;
        else 
            squashed_v_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    squashed_v_ce2 <= squashed_v_ce2_local;

    squashed_v_ce2_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            squashed_v_ce2_local <= ap_const_logic_1;
        else 
            squashed_v_ce2_local <= ap_const_logic_0;
        end if; 
    end process;

    squashed_v_ce3 <= squashed_v_ce3_local;

    squashed_v_ce3_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            squashed_v_ce3_local <= ap_const_logic_1;
        else 
            squashed_v_ce3_local <= ap_const_logic_0;
        end if; 
    end process;

    squashed_v_ce4 <= squashed_v_ce4_local;

    squashed_v_ce4_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            squashed_v_ce4_local <= ap_const_logic_1;
        else 
            squashed_v_ce4_local <= ap_const_logic_0;
        end if; 
    end process;

    squashed_v_ce5 <= squashed_v_ce5_local;

    squashed_v_ce5_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            squashed_v_ce5_local <= ap_const_logic_1;
        else 
            squashed_v_ce5_local <= ap_const_logic_0;
        end if; 
    end process;

    squashed_v_ce6 <= squashed_v_ce6_local;

    squashed_v_ce6_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            squashed_v_ce6_local <= ap_const_logic_1;
        else 
            squashed_v_ce6_local <= ap_const_logic_0;
        end if; 
    end process;

    squashed_v_ce7 <= squashed_v_ce7_local;

    squashed_v_ce7_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            squashed_v_ce7_local <= ap_const_logic_1;
        else 
            squashed_v_ce7_local <= ap_const_logic_0;
        end if; 
    end process;

    squashed_v_ce8 <= squashed_v_ce8_local;

    squashed_v_ce8_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            squashed_v_ce8_local <= ap_const_logic_1;
        else 
            squashed_v_ce8_local <= ap_const_logic_0;
        end if; 
    end process;

    squashed_v_ce9 <= squashed_v_ce9_local;

    squashed_v_ce9_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            squashed_v_ce9_local <= ap_const_logic_1;
        else 
            squashed_v_ce9_local <= ap_const_logic_0;
        end if; 
    end process;

        squashed_v_load_10_cast_fu_1095_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(squashed_v_load_9_reg_1862),48));

        squashed_v_load_11_cast_fu_1099_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(squashed_v_load_10_reg_1867),48));

        squashed_v_load_12_cast_fu_1204_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(squashed_v_load_11_reg_1937),48));

        squashed_v_load_13_cast_fu_1208_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(squashed_v_load_12_reg_1942),48));

        squashed_v_load_14_cast_fu_1286_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(squashed_v_load_13_reg_2012),48));

        squashed_v_load_15_cast_fu_1290_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(squashed_v_load_14_reg_2017),48));

        squashed_v_load_1_cast_fu_815_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(squashed_v_load_reg_1571),48));

        squashed_v_load_2_cast_fu_819_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(squashed_v_load_1_reg_1576),48));

        squashed_v_load_3_cast_fu_823_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(squashed_v_load_2_reg_1581),48));

        squashed_v_load_4_cast_fu_863_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(squashed_v_load_3_reg_1636),48));

        squashed_v_load_5_cast_fu_867_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(squashed_v_load_4_reg_1641),48));

        squashed_v_load_6_cast_fu_925_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(squashed_v_load_5_reg_1701),48));

        squashed_v_load_7_cast_fu_929_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(squashed_v_load_6_reg_1706),48));

        squashed_v_load_8_cast_fu_1010_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(squashed_v_load_7_reg_1787),48));

        squashed_v_load_9_cast_fu_1014_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(squashed_v_load_8_reg_1792),48));

    tmp_115_fu_716_p3 <= (select_ln286_1_reg_1503 & ap_const_lv8_0);
    tmp_16_fu_697_p3 <= (select_ln286_1_reg_1503 & ap_const_lv4_0);
    tmp_17_fu_733_p3 <= (select_ln286_1_reg_1503 & ap_const_lv4_1);
    tmp_18_fu_745_p3 <= (select_ln286_1_reg_1503 & ap_const_lv4_2);
    tmp_19_fu_791_p3 <= (select_ln286_1_reg_1503_pp0_iter2_reg & ap_const_lv4_3);
    tmp_20_fu_803_p3 <= (select_ln286_1_reg_1503_pp0_iter2_reg & ap_const_lv4_4);
    tmp_21_fu_827_p3 <= (select_ln286_1_reg_1503_pp0_iter3_reg & ap_const_lv4_5);
    tmp_22_fu_839_p3 <= (select_ln286_1_reg_1503_pp0_iter3_reg & ap_const_lv4_6);
    tmp_23_fu_871_p3 <= (select_ln286_1_reg_1503_pp0_iter4_reg & ap_const_lv4_7);
    tmp_24_fu_883_p3 <= (select_ln286_1_reg_1503_pp0_iter4_reg & ap_const_lv4_8);
    tmp_25_fu_933_p3 <= (select_ln286_1_reg_1503_pp0_iter5_reg & ap_const_lv4_9);
    tmp_26_fu_945_p3 <= (select_ln286_1_reg_1503_pp0_iter5_reg & ap_const_lv4_A);
    tmp_27_fu_1018_p3 <= (select_ln286_1_reg_1503_pp0_iter6_reg & ap_const_lv4_B);
    tmp_28_fu_1030_p3 <= (select_ln286_1_reg_1503_pp0_iter6_reg & ap_const_lv4_C);
    tmp_29_fu_1103_p3 <= (select_ln286_1_reg_1503_pp0_iter7_reg & ap_const_lv4_D);
    tmp_30_fu_1115_p3 <= (select_ln286_1_reg_1503_pp0_iter7_reg & ap_const_lv4_E);
    tmp_31_fu_1212_p3 <= (select_ln286_1_reg_1503_pp0_iter8_reg & ap_const_lv4_F);
    tmp_33_fu_969_p4 <= add_ln294_fu_964_p2(47 downto 16);
    tmp_35_fu_1054_p4 <= add_ln294_2_fu_1049_p2(47 downto 16);
    tmp_37_fu_1139_p4 <= add_ln294_4_fu_1134_p2(47 downto 16);
    tmp_40_fu_1239_p4 <= add_ln294_6_fu_1234_p2(47 downto 16);
    tmp_42_fu_1306_p4 <= add_ln294_8_fu_1301_p2(47 downto 16);
    tmp_44_fu_1363_p4 <= add_ln294_10_fu_1358_p2(47 downto 16);
    tmp_46_fu_1412_p4 <= add_ln294_12_fu_1407_p2(47 downto 16);
    tmp_fu_1187_p3 <= (select_ln286_1_reg_1503_pp0_iter8_reg & ap_const_lv7_0);
    weighted_input_u_1_address0 <= zext_ln294_1_reg_1761(15 - 1 downto 0);
    weighted_input_u_1_address1 <= zext_ln294_fu_774_p1(15 - 1 downto 0);
    weighted_input_u_1_ce0 <= weighted_input_u_1_ce0_local;

    weighted_input_u_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            weighted_input_u_1_ce0_local <= ap_const_logic_1;
        else 
            weighted_input_u_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weighted_input_u_1_ce1 <= weighted_input_u_1_ce1_local;

    weighted_input_u_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            weighted_input_u_1_ce1_local <= ap_const_logic_1;
        else 
            weighted_input_u_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    weighted_input_u_2_address0 <= zext_ln294_1_reg_1761(15 - 1 downto 0);
    weighted_input_u_2_address1 <= zext_ln294_fu_774_p1(15 - 1 downto 0);
    weighted_input_u_2_ce0 <= weighted_input_u_2_ce0_local;

    weighted_input_u_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            weighted_input_u_2_ce0_local <= ap_const_logic_1;
        else 
            weighted_input_u_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weighted_input_u_2_ce1 <= weighted_input_u_2_ce1_local;

    weighted_input_u_2_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            weighted_input_u_2_ce1_local <= ap_const_logic_1;
        else 
            weighted_input_u_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    weighted_input_u_3_address0 <= zext_ln294_1_reg_1761_pp0_iter6_reg(15 - 1 downto 0);
    weighted_input_u_3_address1 <= zext_ln294_reg_1542(15 - 1 downto 0);
    weighted_input_u_3_ce0 <= weighted_input_u_3_ce0_local;

    weighted_input_u_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            weighted_input_u_3_ce0_local <= ap_const_logic_1;
        else 
            weighted_input_u_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weighted_input_u_3_ce1 <= weighted_input_u_3_ce1_local;

    weighted_input_u_3_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            weighted_input_u_3_ce1_local <= ap_const_logic_1;
        else 
            weighted_input_u_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    weighted_input_u_4_address0 <= zext_ln294_1_reg_1761_pp0_iter6_reg(15 - 1 downto 0);
    weighted_input_u_4_address1 <= zext_ln294_reg_1542(15 - 1 downto 0);
    weighted_input_u_4_ce0 <= weighted_input_u_4_ce0_local;

    weighted_input_u_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            weighted_input_u_4_ce0_local <= ap_const_logic_1;
        else 
            weighted_input_u_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weighted_input_u_4_ce1 <= weighted_input_u_4_ce1_local;

    weighted_input_u_4_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            weighted_input_u_4_ce1_local <= ap_const_logic_1;
        else 
            weighted_input_u_4_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    weighted_input_u_5_address0 <= zext_ln294_1_reg_1761_pp0_iter7_reg(15 - 1 downto 0);
    weighted_input_u_5_address1 <= zext_ln294_reg_1542_pp0_iter3_reg(15 - 1 downto 0);
    weighted_input_u_5_ce0 <= weighted_input_u_5_ce0_local;

    weighted_input_u_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            weighted_input_u_5_ce0_local <= ap_const_logic_1;
        else 
            weighted_input_u_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weighted_input_u_5_ce1 <= weighted_input_u_5_ce1_local;

    weighted_input_u_5_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            weighted_input_u_5_ce1_local <= ap_const_logic_1;
        else 
            weighted_input_u_5_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    weighted_input_u_6_address0 <= zext_ln294_1_reg_1761_pp0_iter7_reg(15 - 1 downto 0);
    weighted_input_u_6_address1 <= zext_ln294_reg_1542_pp0_iter3_reg(15 - 1 downto 0);
    weighted_input_u_6_ce0 <= weighted_input_u_6_ce0_local;

    weighted_input_u_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then 
            weighted_input_u_6_ce0_local <= ap_const_logic_1;
        else 
            weighted_input_u_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weighted_input_u_6_ce1 <= weighted_input_u_6_ce1_local;

    weighted_input_u_6_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            weighted_input_u_6_ce1_local <= ap_const_logic_1;
        else 
            weighted_input_u_6_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    weighted_input_u_7_address0 <= zext_ln294_1_reg_1761_pp0_iter8_reg(15 - 1 downto 0);
    weighted_input_u_7_address1 <= zext_ln294_reg_1542_pp0_iter4_reg(15 - 1 downto 0);
    weighted_input_u_7_ce0 <= weighted_input_u_7_ce0_local;

    weighted_input_u_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then 
            weighted_input_u_7_ce0_local <= ap_const_logic_1;
        else 
            weighted_input_u_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weighted_input_u_7_ce1 <= weighted_input_u_7_ce1_local;

    weighted_input_u_7_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            weighted_input_u_7_ce1_local <= ap_const_logic_1;
        else 
            weighted_input_u_7_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    weighted_input_u_address0 <= zext_ln294_1_fu_920_p1(15 - 1 downto 0);
    weighted_input_u_address1 <= zext_ln294_fu_774_p1(15 - 1 downto 0);
    weighted_input_u_ce0 <= weighted_input_u_ce0_local;

    weighted_input_u_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            weighted_input_u_ce0_local <= ap_const_logic_1;
        else 
            weighted_input_u_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    weighted_input_u_ce1 <= weighted_input_u_ce1_local;

    weighted_input_u_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            weighted_input_u_ce1_local <= ap_const_logic_1;
        else 
            weighted_input_u_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln289_fu_1224_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln286_reg_1497_pp0_iter8_reg),14));
    zext_ln294_1_fu_920_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_913_p3),64));
    zext_ln294_fu_774_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_udiv26_fu_768_p2),64));
    zext_ln296_fu_1468_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln296_reg_2067_pp0_iter12_reg),64));
end behav;
