// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module digitcaps_accel_digitcaps_accel_Pipeline_VITIS_LOOP_286_1_VITIS_LOOP_289_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        squashed_v_address0,
        squashed_v_ce0,
        squashed_v_q0,
        squashed_v_address1,
        squashed_v_ce1,
        squashed_v_q1,
        squashed_v_address2,
        squashed_v_ce2,
        squashed_v_q2,
        squashed_v_address3,
        squashed_v_ce3,
        squashed_v_q3,
        squashed_v_address4,
        squashed_v_ce4,
        squashed_v_q4,
        squashed_v_address5,
        squashed_v_ce5,
        squashed_v_q5,
        squashed_v_address6,
        squashed_v_ce6,
        squashed_v_q6,
        squashed_v_address7,
        squashed_v_ce7,
        squashed_v_q7,
        squashed_v_address8,
        squashed_v_ce8,
        squashed_v_q8,
        squashed_v_address9,
        squashed_v_ce9,
        squashed_v_q9,
        squashed_v_address10,
        squashed_v_ce10,
        squashed_v_q10,
        squashed_v_address11,
        squashed_v_ce11,
        squashed_v_q11,
        squashed_v_address12,
        squashed_v_ce12,
        squashed_v_q12,
        squashed_v_address13,
        squashed_v_ce13,
        squashed_v_q13,
        squashed_v_address14,
        squashed_v_ce14,
        squashed_v_q14,
        squashed_v_address15,
        squashed_v_ce15,
        squashed_v_q15,
        weighted_input_u_address0,
        weighted_input_u_ce0,
        weighted_input_u_q0,
        weighted_input_u_address1,
        weighted_input_u_ce1,
        weighted_input_u_q1,
        weighted_input_u_1_address0,
        weighted_input_u_1_ce0,
        weighted_input_u_1_q0,
        weighted_input_u_1_address1,
        weighted_input_u_1_ce1,
        weighted_input_u_1_q1,
        weighted_input_u_2_address0,
        weighted_input_u_2_ce0,
        weighted_input_u_2_q0,
        weighted_input_u_2_address1,
        weighted_input_u_2_ce1,
        weighted_input_u_2_q1,
        weighted_input_u_3_address0,
        weighted_input_u_3_ce0,
        weighted_input_u_3_q0,
        weighted_input_u_3_address1,
        weighted_input_u_3_ce1,
        weighted_input_u_3_q1,
        weighted_input_u_4_address0,
        weighted_input_u_4_ce0,
        weighted_input_u_4_q0,
        weighted_input_u_4_address1,
        weighted_input_u_4_ce1,
        weighted_input_u_4_q1,
        weighted_input_u_5_address0,
        weighted_input_u_5_ce0,
        weighted_input_u_5_q0,
        weighted_input_u_5_address1,
        weighted_input_u_5_ce1,
        weighted_input_u_5_q1,
        weighted_input_u_6_address0,
        weighted_input_u_6_ce0,
        weighted_input_u_6_q0,
        weighted_input_u_6_address1,
        weighted_input_u_6_ce1,
        weighted_input_u_6_q1,
        weighted_input_u_7_address0,
        weighted_input_u_7_ce0,
        weighted_input_u_7_q0,
        weighted_input_u_7_address1,
        weighted_input_u_7_ce1,
        weighted_input_u_7_q1,
        output_agreement_address0,
        output_agreement_ce0,
        output_agreement_we0,
        output_agreement_d0,
        grp_fu_531_p_din0,
        grp_fu_531_p_din1,
        grp_fu_531_p_dout0,
        grp_fu_531_p_ce,
        grp_fu_535_p_din0,
        grp_fu_535_p_din1,
        grp_fu_535_p_dout0,
        grp_fu_535_p_ce,
        grp_fu_539_p_din0,
        grp_fu_539_p_din1,
        grp_fu_539_p_dout0,
        grp_fu_539_p_ce,
        grp_fu_543_p_din0,
        grp_fu_543_p_din1,
        grp_fu_543_p_dout0,
        grp_fu_543_p_ce,
        grp_fu_547_p_din0,
        grp_fu_547_p_din1,
        grp_fu_547_p_dout0,
        grp_fu_547_p_ce,
        grp_fu_551_p_din0,
        grp_fu_551_p_din1,
        grp_fu_551_p_dout0,
        grp_fu_551_p_ce,
        grp_fu_555_p_din0,
        grp_fu_555_p_din1,
        grp_fu_555_p_dout0,
        grp_fu_555_p_ce,
        grp_fu_559_p_din0,
        grp_fu_559_p_din1,
        grp_fu_559_p_dout0,
        grp_fu_559_p_ce,
        grp_fu_563_p_din0,
        grp_fu_563_p_din1,
        grp_fu_563_p_dout0,
        grp_fu_563_p_ce,
        grp_fu_567_p_din0,
        grp_fu_567_p_din1,
        grp_fu_567_p_dout0,
        grp_fu_567_p_ce,
        grp_fu_571_p_din0,
        grp_fu_571_p_din1,
        grp_fu_571_p_dout0,
        grp_fu_571_p_ce,
        grp_fu_575_p_din0,
        grp_fu_575_p_din1,
        grp_fu_575_p_dout0,
        grp_fu_575_p_ce,
        grp_fu_579_p_din0,
        grp_fu_579_p_din1,
        grp_fu_579_p_dout0,
        grp_fu_579_p_ce,
        grp_fu_583_p_din0,
        grp_fu_583_p_din1,
        grp_fu_583_p_dout0,
        grp_fu_583_p_ce,
        grp_fu_587_p_din0,
        grp_fu_587_p_din1,
        grp_fu_587_p_dout0,
        grp_fu_587_p_ce,
        grp_fu_591_p_din0,
        grp_fu_591_p_din1,
        grp_fu_591_p_dout0,
        grp_fu_591_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] squashed_v_address0;
output   squashed_v_ce0;
input  [31:0] squashed_v_q0;
output  [7:0] squashed_v_address1;
output   squashed_v_ce1;
input  [31:0] squashed_v_q1;
output  [7:0] squashed_v_address2;
output   squashed_v_ce2;
input  [31:0] squashed_v_q2;
output  [7:0] squashed_v_address3;
output   squashed_v_ce3;
input  [31:0] squashed_v_q3;
output  [7:0] squashed_v_address4;
output   squashed_v_ce4;
input  [31:0] squashed_v_q4;
output  [7:0] squashed_v_address5;
output   squashed_v_ce5;
input  [31:0] squashed_v_q5;
output  [7:0] squashed_v_address6;
output   squashed_v_ce6;
input  [31:0] squashed_v_q6;
output  [7:0] squashed_v_address7;
output   squashed_v_ce7;
input  [31:0] squashed_v_q7;
output  [7:0] squashed_v_address8;
output   squashed_v_ce8;
input  [31:0] squashed_v_q8;
output  [7:0] squashed_v_address9;
output   squashed_v_ce9;
input  [31:0] squashed_v_q9;
output  [7:0] squashed_v_address10;
output   squashed_v_ce10;
input  [31:0] squashed_v_q10;
output  [7:0] squashed_v_address11;
output   squashed_v_ce11;
input  [31:0] squashed_v_q11;
output  [7:0] squashed_v_address12;
output   squashed_v_ce12;
input  [31:0] squashed_v_q12;
output  [7:0] squashed_v_address13;
output   squashed_v_ce13;
input  [31:0] squashed_v_q13;
output  [7:0] squashed_v_address14;
output   squashed_v_ce14;
input  [31:0] squashed_v_q14;
output  [7:0] squashed_v_address15;
output   squashed_v_ce15;
input  [31:0] squashed_v_q15;
output  [14:0] weighted_input_u_address0;
output   weighted_input_u_ce0;
input  [31:0] weighted_input_u_q0;
output  [14:0] weighted_input_u_address1;
output   weighted_input_u_ce1;
input  [31:0] weighted_input_u_q1;
output  [14:0] weighted_input_u_1_address0;
output   weighted_input_u_1_ce0;
input  [31:0] weighted_input_u_1_q0;
output  [14:0] weighted_input_u_1_address1;
output   weighted_input_u_1_ce1;
input  [31:0] weighted_input_u_1_q1;
output  [14:0] weighted_input_u_2_address0;
output   weighted_input_u_2_ce0;
input  [31:0] weighted_input_u_2_q0;
output  [14:0] weighted_input_u_2_address1;
output   weighted_input_u_2_ce1;
input  [31:0] weighted_input_u_2_q1;
output  [14:0] weighted_input_u_3_address0;
output   weighted_input_u_3_ce0;
input  [31:0] weighted_input_u_3_q0;
output  [14:0] weighted_input_u_3_address1;
output   weighted_input_u_3_ce1;
input  [31:0] weighted_input_u_3_q1;
output  [14:0] weighted_input_u_4_address0;
output   weighted_input_u_4_ce0;
input  [31:0] weighted_input_u_4_q0;
output  [14:0] weighted_input_u_4_address1;
output   weighted_input_u_4_ce1;
input  [31:0] weighted_input_u_4_q1;
output  [14:0] weighted_input_u_5_address0;
output   weighted_input_u_5_ce0;
input  [31:0] weighted_input_u_5_q0;
output  [14:0] weighted_input_u_5_address1;
output   weighted_input_u_5_ce1;
input  [31:0] weighted_input_u_5_q1;
output  [14:0] weighted_input_u_6_address0;
output   weighted_input_u_6_ce0;
input  [31:0] weighted_input_u_6_q0;
output  [14:0] weighted_input_u_6_address1;
output   weighted_input_u_6_ce1;
input  [31:0] weighted_input_u_6_q1;
output  [14:0] weighted_input_u_7_address0;
output   weighted_input_u_7_ce0;
input  [31:0] weighted_input_u_7_q0;
output  [14:0] weighted_input_u_7_address1;
output   weighted_input_u_7_ce1;
input  [31:0] weighted_input_u_7_q1;
output  [13:0] output_agreement_address0;
output   output_agreement_ce0;
output   output_agreement_we0;
output  [31:0] output_agreement_d0;
output  [31:0] grp_fu_531_p_din0;
output  [31:0] grp_fu_531_p_din1;
input  [47:0] grp_fu_531_p_dout0;
output   grp_fu_531_p_ce;
output  [31:0] grp_fu_535_p_din0;
output  [31:0] grp_fu_535_p_din1;
input  [47:0] grp_fu_535_p_dout0;
output   grp_fu_535_p_ce;
output  [31:0] grp_fu_539_p_din0;
output  [31:0] grp_fu_539_p_din1;
input  [47:0] grp_fu_539_p_dout0;
output   grp_fu_539_p_ce;
output  [31:0] grp_fu_543_p_din0;
output  [31:0] grp_fu_543_p_din1;
input  [47:0] grp_fu_543_p_dout0;
output   grp_fu_543_p_ce;
output  [31:0] grp_fu_547_p_din0;
output  [31:0] grp_fu_547_p_din1;
input  [47:0] grp_fu_547_p_dout0;
output   grp_fu_547_p_ce;
output  [31:0] grp_fu_551_p_din0;
output  [31:0] grp_fu_551_p_din1;
input  [47:0] grp_fu_551_p_dout0;
output   grp_fu_551_p_ce;
output  [31:0] grp_fu_555_p_din0;
output  [31:0] grp_fu_555_p_din1;
input  [47:0] grp_fu_555_p_dout0;
output   grp_fu_555_p_ce;
output  [31:0] grp_fu_559_p_din0;
output  [31:0] grp_fu_559_p_din1;
input  [47:0] grp_fu_559_p_dout0;
output   grp_fu_559_p_ce;
output  [31:0] grp_fu_563_p_din0;
output  [31:0] grp_fu_563_p_din1;
input  [47:0] grp_fu_563_p_dout0;
output   grp_fu_563_p_ce;
output  [31:0] grp_fu_567_p_din0;
output  [31:0] grp_fu_567_p_din1;
input  [47:0] grp_fu_567_p_dout0;
output   grp_fu_567_p_ce;
output  [31:0] grp_fu_571_p_din0;
output  [31:0] grp_fu_571_p_din1;
input  [47:0] grp_fu_571_p_dout0;
output   grp_fu_571_p_ce;
output  [31:0] grp_fu_575_p_din0;
output  [31:0] grp_fu_575_p_din1;
input  [47:0] grp_fu_575_p_dout0;
output   grp_fu_575_p_ce;
output  [31:0] grp_fu_579_p_din0;
output  [31:0] grp_fu_579_p_din1;
input  [47:0] grp_fu_579_p_dout0;
output   grp_fu_579_p_ce;
output  [31:0] grp_fu_583_p_din0;
output  [31:0] grp_fu_583_p_din1;
input  [47:0] grp_fu_583_p_dout0;
output   grp_fu_583_p_ce;
output  [31:0] grp_fu_587_p_din0;
output  [31:0] grp_fu_587_p_din1;
input  [47:0] grp_fu_587_p_dout0;
output   grp_fu_587_p_ce;
output  [31:0] grp_fu_591_p_din0;
output  [31:0] grp_fu_591_p_din1;
input  [47:0] grp_fu_591_p_dout0;
output   grp_fu_591_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln286_fu_630_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [10:0] select_ln286_fu_659_p3;
reg   [10:0] select_ln286_reg_1497;
reg   [10:0] select_ln286_reg_1497_pp0_iter2_reg;
reg   [10:0] select_ln286_reg_1497_pp0_iter3_reg;
reg   [10:0] select_ln286_reg_1497_pp0_iter4_reg;
reg   [10:0] select_ln286_reg_1497_pp0_iter5_reg;
reg   [10:0] select_ln286_reg_1497_pp0_iter6_reg;
reg   [10:0] select_ln286_reg_1497_pp0_iter7_reg;
reg   [10:0] select_ln286_reg_1497_pp0_iter8_reg;
wire   [3:0] select_ln286_1_fu_673_p3;
reg   [3:0] select_ln286_1_reg_1503;
reg   [3:0] select_ln286_1_reg_1503_pp0_iter2_reg;
reg   [3:0] select_ln286_1_reg_1503_pp0_iter3_reg;
reg   [3:0] select_ln286_1_reg_1503_pp0_iter4_reg;
reg   [3:0] select_ln286_1_reg_1503_pp0_iter5_reg;
reg   [3:0] select_ln286_1_reg_1503_pp0_iter6_reg;
reg   [3:0] select_ln286_1_reg_1503_pp0_iter7_reg;
reg   [3:0] select_ln286_1_reg_1503_pp0_iter8_reg;
wire   [63:0] zext_ln294_fu_774_p1;
reg   [63:0] zext_ln294_reg_1542;
reg   [63:0] zext_ln294_reg_1542_pp0_iter3_reg;
reg   [63:0] zext_ln294_reg_1542_pp0_iter4_reg;
reg   [13:0] tmp_39_reg_1566;
reg   [13:0] tmp_39_reg_1566_pp0_iter3_reg;
reg   [13:0] tmp_39_reg_1566_pp0_iter4_reg;
reg   [31:0] squashed_v_load_reg_1571;
reg   [31:0] squashed_v_load_1_reg_1576;
reg   [31:0] squashed_v_load_2_reg_1581;
reg   [31:0] weighted_input_u_load_reg_1596;
reg   [31:0] weighted_input_u_1_load_reg_1601;
reg   [31:0] weighted_input_u_2_load_reg_1606;
wire  signed [47:0] squashed_v_load_1_cast_fu_815_p1;
wire  signed [47:0] squashed_v_load_2_cast_fu_819_p1;
wire  signed [47:0] squashed_v_load_3_cast_fu_823_p1;
reg   [31:0] squashed_v_load_3_reg_1636;
reg   [31:0] squashed_v_load_4_reg_1641;
wire  signed [47:0] sext_ln294_fu_851_p1;
wire  signed [47:0] sext_ln294_1_fu_855_p1;
wire  signed [47:0] sext_ln294_2_fu_859_p1;
reg   [31:0] weighted_input_u_3_load_reg_1671;
reg   [31:0] weighted_input_u_4_load_reg_1676;
wire  signed [47:0] squashed_v_load_4_cast_fu_863_p1;
wire  signed [47:0] squashed_v_load_5_cast_fu_867_p1;
reg   [31:0] squashed_v_load_5_reg_1701;
reg   [31:0] squashed_v_load_6_reg_1706;
reg   [47:0] mul_ln294_1_reg_1721;
reg   [31:0] tmp_32_reg_1726;
reg   [47:0] mul_ln294_2_reg_1731;
wire  signed [47:0] sext_ln294_3_fu_905_p1;
wire  signed [47:0] sext_ln294_4_fu_909_p1;
reg   [31:0] weighted_input_u_5_load_reg_1746;
reg   [31:0] weighted_input_u_6_load_reg_1751;
wire   [63:0] zext_ln294_1_fu_920_p1;
reg   [63:0] zext_ln294_1_reg_1761;
reg   [63:0] zext_ln294_1_reg_1761_pp0_iter6_reg;
reg   [63:0] zext_ln294_1_reg_1761_pp0_iter7_reg;
reg   [63:0] zext_ln294_1_reg_1761_pp0_iter8_reg;
wire  signed [47:0] squashed_v_load_6_cast_fu_925_p1;
wire  signed [47:0] squashed_v_load_7_cast_fu_929_p1;
reg   [31:0] squashed_v_load_7_reg_1787;
reg   [31:0] squashed_v_load_8_reg_1792;
reg   [47:0] mul_ln294_3_reg_1807;
reg   [31:0] tmp_34_reg_1812;
reg   [47:0] mul_ln294_4_reg_1817;
wire  signed [47:0] sext_ln294_5_fu_1002_p1;
wire  signed [47:0] sext_ln294_6_fu_1006_p1;
reg   [31:0] weighted_input_u_7_load_reg_1832;
reg   [31:0] weighted_input_u_load_1_reg_1837;
wire  signed [47:0] squashed_v_load_8_cast_fu_1010_p1;
wire  signed [47:0] squashed_v_load_9_cast_fu_1014_p1;
reg   [31:0] squashed_v_load_9_reg_1862;
reg   [31:0] squashed_v_load_10_reg_1867;
reg   [47:0] mul_ln294_5_reg_1882;
reg   [31:0] tmp_36_reg_1887;
reg   [47:0] mul_ln294_6_reg_1892;
wire  signed [47:0] sext_ln294_7_fu_1087_p1;
wire  signed [47:0] sext_ln294_8_fu_1091_p1;
reg   [31:0] weighted_input_u_1_load_1_reg_1907;
reg   [31:0] weighted_input_u_2_load_1_reg_1912;
wire  signed [47:0] squashed_v_load_10_cast_fu_1095_p1;
wire  signed [47:0] squashed_v_load_11_cast_fu_1099_p1;
reg   [31:0] squashed_v_load_11_reg_1937;
reg   [31:0] squashed_v_load_12_reg_1942;
reg   [47:0] mul_ln294_7_reg_1957;
reg   [31:0] tmp_38_reg_1962;
reg   [47:0] mul_ln294_8_reg_1967;
wire  signed [47:0] sext_ln294_9_fu_1172_p1;
wire  signed [47:0] sext_ln294_10_fu_1176_p1;
reg   [31:0] weighted_input_u_3_load_1_reg_1982;
reg   [31:0] weighted_input_u_4_load_1_reg_1987;
wire  signed [47:0] squashed_v_load_12_cast_fu_1204_p1;
wire  signed [47:0] squashed_v_load_13_cast_fu_1208_p1;
reg   [31:0] squashed_v_load_13_reg_2012;
reg   [31:0] squashed_v_load_14_reg_2017;
reg   [47:0] mul_ln294_9_reg_2027;
reg   [31:0] tmp_41_reg_2032;
reg   [47:0] mul_ln294_10_reg_2037;
wire  signed [47:0] sext_ln294_11_fu_1272_p1;
wire  signed [47:0] sext_ln294_12_fu_1276_p1;
reg   [31:0] weighted_input_u_5_load_1_reg_2052;
reg   [31:0] weighted_input_u_6_load_1_reg_2057;
wire   [13:0] add_ln296_fu_1280_p2;
reg   [13:0] add_ln296_reg_2067;
reg   [13:0] add_ln296_reg_2067_pp0_iter10_reg;
reg   [13:0] add_ln296_reg_2067_pp0_iter11_reg;
reg   [13:0] add_ln296_reg_2067_pp0_iter12_reg;
wire  signed [47:0] squashed_v_load_14_cast_fu_1286_p1;
wire  signed [47:0] squashed_v_load_15_cast_fu_1290_p1;
reg   [31:0] squashed_v_load_15_reg_2082;
reg   [47:0] mul_ln294_11_reg_2087;
reg   [31:0] tmp_43_reg_2092;
reg   [47:0] mul_ln294_12_reg_2097;
wire  signed [47:0] sext_ln294_13_fu_1339_p1;
wire  signed [47:0] sext_ln294_14_fu_1343_p1;
reg   [31:0] weighted_input_u_7_load_1_reg_2112;
wire  signed [47:0] sext_ln289_fu_1347_p1;
reg   [47:0] mul_ln294_13_reg_2122;
reg   [31:0] tmp_45_reg_2127;
reg   [47:0] mul_ln294_14_reg_2132;
wire  signed [47:0] sext_ln294_15_fu_1396_p1;
reg   [47:0] mul_ln294_15_reg_2142;
reg   [31:0] tmp_47_reg_2147;
wire   [63:0] p_cast15_fu_704_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] p_cast16_fu_740_p1;
wire   [63:0] p_cast17_fu_752_p1;
wire   [63:0] p_cast18_fu_798_p1;
wire   [63:0] p_cast19_fu_810_p1;
wire   [63:0] p_cast20_fu_834_p1;
wire   [63:0] p_cast21_fu_846_p1;
wire   [63:0] p_cast22_fu_878_p1;
wire   [63:0] p_cast23_fu_890_p1;
wire   [63:0] p_cast24_fu_940_p1;
wire   [63:0] p_cast25_fu_952_p1;
wire   [63:0] p_cast26_fu_1025_p1;
wire   [63:0] p_cast27_fu_1037_p1;
wire   [63:0] p_cast28_fu_1110_p1;
wire   [63:0] p_cast29_fu_1122_p1;
wire   [63:0] p_cast30_fu_1219_p1;
wire   [63:0] zext_ln296_fu_1468_p1;
reg   [10:0] j_fu_130;
wire   [10:0] add_ln289_fu_681_p2;
wire    ap_loop_init;
reg   [3:0] i_1_fu_134;
reg   [13:0] indvar_flatten20_fu_138;
wire   [13:0] add_ln286_fu_636_p2;
reg   [13:0] ap_sig_allocacmp_indvar_flatten20_load;
reg    squashed_v_ce15_local;
reg    squashed_v_ce14_local;
reg    squashed_v_ce13_local;
reg    squashed_v_ce12_local;
reg    squashed_v_ce11_local;
reg    squashed_v_ce10_local;
reg    squashed_v_ce9_local;
reg    squashed_v_ce8_local;
reg    squashed_v_ce7_local;
reg    squashed_v_ce6_local;
reg    squashed_v_ce5_local;
reg    squashed_v_ce4_local;
reg    squashed_v_ce3_local;
reg    squashed_v_ce2_local;
reg    squashed_v_ce1_local;
reg    squashed_v_ce0_local;
reg    weighted_input_u_ce1_local;
reg    weighted_input_u_ce0_local;
reg    weighted_input_u_1_ce1_local;
reg    weighted_input_u_1_ce0_local;
reg    weighted_input_u_2_ce1_local;
reg    weighted_input_u_2_ce0_local;
reg    weighted_input_u_3_ce1_local;
reg    weighted_input_u_3_ce0_local;
reg    weighted_input_u_4_ce1_local;
reg    weighted_input_u_4_ce0_local;
reg    weighted_input_u_5_ce1_local;
reg    weighted_input_u_5_ce0_local;
reg    weighted_input_u_6_ce1_local;
reg    weighted_input_u_6_ce0_local;
reg    weighted_input_u_7_ce1_local;
reg    weighted_input_u_7_ce0_local;
reg    output_agreement_we0_local;
reg    output_agreement_ce0_local;
wire   [0:0] icmp_ln289_fu_653_p2;
wire   [3:0] add_ln286_1_fu_667_p2;
wire   [7:0] tmp_16_fu_697_p3;
wire   [11:0] tmp_115_fu_716_p3;
wire   [14:0] p_shl_fu_709_p3;
wire   [14:0] p_shl31_fu_723_p1;
wire   [7:0] tmp_17_fu_733_p3;
wire   [7:0] tmp_18_fu_745_p3;
wire   [11:0] p_udiv_fu_757_p3;
wire   [14:0] p_udiv2527_cast_fu_764_p1;
wire   [14:0] p_udiv2428_fu_727_p2;
wire   [14:0] p_udiv26_fu_768_p2;
wire   [7:0] tmp_19_fu_791_p3;
wire   [7:0] tmp_20_fu_803_p3;
wire   [7:0] tmp_21_fu_827_p3;
wire   [7:0] tmp_22_fu_839_p3;
wire   [7:0] tmp_23_fu_871_p3;
wire   [7:0] tmp_24_fu_883_p3;
wire   [14:0] or_ln_fu_913_p3;
wire   [7:0] tmp_25_fu_933_p3;
wire   [7:0] tmp_26_fu_945_p3;
wire   [47:0] shl_ln2_fu_957_p3;
wire   [47:0] add_ln294_fu_964_p2;
wire   [31:0] tmp_33_fu_969_p4;
wire   [47:0] shl_ln294_1_fu_979_p3;
wire   [47:0] add_ln294_1_fu_987_p2;
wire   [7:0] tmp_27_fu_1018_p3;
wire   [7:0] tmp_28_fu_1030_p3;
wire   [47:0] shl_ln294_2_fu_1042_p3;
wire   [47:0] add_ln294_2_fu_1049_p2;
wire   [31:0] tmp_35_fu_1054_p4;
wire   [47:0] shl_ln294_3_fu_1064_p3;
wire   [47:0] add_ln294_3_fu_1072_p2;
wire   [7:0] tmp_29_fu_1103_p3;
wire   [7:0] tmp_30_fu_1115_p3;
wire   [47:0] shl_ln294_4_fu_1127_p3;
wire   [47:0] add_ln294_4_fu_1134_p2;
wire   [31:0] tmp_37_fu_1139_p4;
wire   [47:0] shl_ln294_5_fu_1149_p3;
wire   [47:0] add_ln294_5_fu_1157_p2;
wire   [10:0] tmp_fu_1187_p3;
wire   [13:0] p_shl1_fu_1180_p3;
wire   [13:0] p_shl33_fu_1194_p1;
wire   [7:0] tmp_31_fu_1212_p3;
wire   [47:0] shl_ln294_6_fu_1227_p3;
wire   [47:0] add_ln294_6_fu_1234_p2;
wire   [31:0] tmp_40_fu_1239_p4;
wire   [47:0] shl_ln294_7_fu_1249_p3;
wire   [47:0] add_ln294_7_fu_1257_p2;
wire   [13:0] zext_ln289_fu_1224_p1;
wire   [13:0] empty_fu_1198_p2;
wire   [47:0] shl_ln294_8_fu_1294_p3;
wire   [47:0] add_ln294_8_fu_1301_p2;
wire   [31:0] tmp_42_fu_1306_p4;
wire   [47:0] shl_ln294_9_fu_1316_p3;
wire   [47:0] add_ln294_9_fu_1324_p2;
wire   [47:0] shl_ln294_s_fu_1351_p3;
wire   [47:0] add_ln294_10_fu_1358_p2;
wire   [31:0] tmp_44_fu_1363_p4;
wire   [47:0] shl_ln294_10_fu_1373_p3;
wire   [47:0] add_ln294_11_fu_1381_p2;
wire   [47:0] shl_ln294_11_fu_1400_p3;
wire   [47:0] add_ln294_12_fu_1407_p2;
wire   [31:0] tmp_46_fu_1412_p4;
wire   [47:0] shl_ln294_12_fu_1422_p3;
wire   [47:0] add_ln294_13_fu_1430_p2;
wire   [47:0] shl_ln294_13_fu_1445_p3;
wire   [47:0] add_ln294_14_fu_1452_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 j_fu_130 = 11'd0;
#0 i_1_fu_134 = 4'd0;
#0 indvar_flatten20_fu_138 = 14'd0;
#0 ap_done_reg = 1'b0;
end

digitcaps_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter12_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_1_fu_134 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_1_fu_134 <= select_ln286_1_fu_673_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln286_fu_630_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten20_fu_138 <= add_ln286_fu_636_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten20_fu_138 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_130 <= 11'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            j_fu_130 <= add_ln289_fu_681_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln296_reg_2067 <= add_ln296_fu_1280_p2;
        add_ln296_reg_2067_pp0_iter10_reg <= add_ln296_reg_2067;
        add_ln296_reg_2067_pp0_iter11_reg <= add_ln296_reg_2067_pp0_iter10_reg;
        add_ln296_reg_2067_pp0_iter12_reg <= add_ln296_reg_2067_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        mul_ln294_10_reg_2037 <= grp_fu_571_p_dout0;
        mul_ln294_11_reg_2087 <= grp_fu_575_p_dout0;
        mul_ln294_12_reg_2097 <= grp_fu_579_p_dout0;
        mul_ln294_13_reg_2122 <= grp_fu_583_p_dout0;
        mul_ln294_14_reg_2132 <= grp_fu_587_p_dout0;
        mul_ln294_15_reg_2142 <= grp_fu_591_p_dout0;
        mul_ln294_1_reg_1721 <= grp_fu_535_p_dout0;
        mul_ln294_2_reg_1731 <= grp_fu_539_p_dout0;
        mul_ln294_3_reg_1807 <= grp_fu_543_p_dout0;
        mul_ln294_4_reg_1817 <= grp_fu_547_p_dout0;
        mul_ln294_5_reg_1882 <= grp_fu_551_p_dout0;
        mul_ln294_6_reg_1892 <= grp_fu_555_p_dout0;
        mul_ln294_7_reg_1957 <= grp_fu_559_p_dout0;
        mul_ln294_8_reg_1967 <= grp_fu_563_p_dout0;
        mul_ln294_9_reg_2027 <= grp_fu_567_p_dout0;
        select_ln286_1_reg_1503_pp0_iter2_reg <= select_ln286_1_reg_1503;
        select_ln286_1_reg_1503_pp0_iter3_reg <= select_ln286_1_reg_1503_pp0_iter2_reg;
        select_ln286_1_reg_1503_pp0_iter4_reg <= select_ln286_1_reg_1503_pp0_iter3_reg;
        select_ln286_1_reg_1503_pp0_iter5_reg <= select_ln286_1_reg_1503_pp0_iter4_reg;
        select_ln286_1_reg_1503_pp0_iter6_reg <= select_ln286_1_reg_1503_pp0_iter5_reg;
        select_ln286_1_reg_1503_pp0_iter7_reg <= select_ln286_1_reg_1503_pp0_iter6_reg;
        select_ln286_1_reg_1503_pp0_iter8_reg <= select_ln286_1_reg_1503_pp0_iter7_reg;
        select_ln286_reg_1497_pp0_iter2_reg <= select_ln286_reg_1497;
        select_ln286_reg_1497_pp0_iter3_reg <= select_ln286_reg_1497_pp0_iter2_reg;
        select_ln286_reg_1497_pp0_iter4_reg <= select_ln286_reg_1497_pp0_iter3_reg;
        select_ln286_reg_1497_pp0_iter5_reg <= select_ln286_reg_1497_pp0_iter4_reg;
        select_ln286_reg_1497_pp0_iter6_reg <= select_ln286_reg_1497_pp0_iter5_reg;
        select_ln286_reg_1497_pp0_iter7_reg <= select_ln286_reg_1497_pp0_iter6_reg;
        select_ln286_reg_1497_pp0_iter8_reg <= select_ln286_reg_1497_pp0_iter7_reg;
        tmp_32_reg_1726 <= {{grp_fu_531_p_dout0[47:16]}};
        tmp_34_reg_1812 <= {{add_ln294_1_fu_987_p2[47:16]}};
        tmp_36_reg_1887 <= {{add_ln294_3_fu_1072_p2[47:16]}};
        tmp_38_reg_1962 <= {{add_ln294_5_fu_1157_p2[47:16]}};
        tmp_39_reg_1566 <= {{p_udiv26_fu_768_p2[14:1]}};
        tmp_39_reg_1566_pp0_iter3_reg <= tmp_39_reg_1566;
        tmp_39_reg_1566_pp0_iter4_reg <= tmp_39_reg_1566_pp0_iter3_reg;
        tmp_41_reg_2032 <= {{add_ln294_7_fu_1257_p2[47:16]}};
        tmp_43_reg_2092 <= {{add_ln294_9_fu_1324_p2[47:16]}};
        tmp_45_reg_2127 <= {{add_ln294_11_fu_1381_p2[47:16]}};
        tmp_47_reg_2147 <= {{add_ln294_13_fu_1430_p2[47:16]}};
        zext_ln294_1_reg_1761[14 : 1] <= zext_ln294_1_fu_920_p1[14 : 1];
        zext_ln294_1_reg_1761_pp0_iter6_reg[14 : 1] <= zext_ln294_1_reg_1761[14 : 1];
        zext_ln294_1_reg_1761_pp0_iter7_reg[14 : 1] <= zext_ln294_1_reg_1761_pp0_iter6_reg[14 : 1];
        zext_ln294_1_reg_1761_pp0_iter8_reg[14 : 1] <= zext_ln294_1_reg_1761_pp0_iter7_reg[14 : 1];
        zext_ln294_reg_1542[14 : 1] <= zext_ln294_fu_774_p1[14 : 1];
        zext_ln294_reg_1542_pp0_iter3_reg[14 : 1] <= zext_ln294_reg_1542[14 : 1];
        zext_ln294_reg_1542_pp0_iter4_reg[14 : 1] <= zext_ln294_reg_1542_pp0_iter3_reg[14 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        select_ln286_1_reg_1503 <= select_ln286_1_fu_673_p3;
        select_ln286_reg_1497 <= select_ln286_fu_659_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        squashed_v_load_10_reg_1867 <= squashed_v_q5;
        squashed_v_load_9_reg_1862 <= squashed_v_q6;
        weighted_input_u_1_load_1_reg_1907 <= weighted_input_u_1_q0;
        weighted_input_u_2_load_1_reg_1912 <= weighted_input_u_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        squashed_v_load_11_reg_1937 <= squashed_v_q4;
        squashed_v_load_12_reg_1942 <= squashed_v_q3;
        weighted_input_u_3_load_1_reg_1982 <= weighted_input_u_3_q0;
        weighted_input_u_4_load_1_reg_1987 <= weighted_input_u_4_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        squashed_v_load_13_reg_2012 <= squashed_v_q2;
        squashed_v_load_14_reg_2017 <= squashed_v_q1;
        weighted_input_u_5_load_1_reg_2052 <= weighted_input_u_5_q0;
        weighted_input_u_6_load_1_reg_2057 <= weighted_input_u_6_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        squashed_v_load_15_reg_2082 <= squashed_v_q0;
        weighted_input_u_7_load_1_reg_2112 <= weighted_input_u_7_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        squashed_v_load_1_reg_1576 <= squashed_v_q14;
        squashed_v_load_2_reg_1581 <= squashed_v_q13;
        squashed_v_load_reg_1571 <= squashed_v_q15;
        weighted_input_u_1_load_reg_1601 <= weighted_input_u_1_q1;
        weighted_input_u_2_load_reg_1606 <= weighted_input_u_2_q1;
        weighted_input_u_load_reg_1596 <= weighted_input_u_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        squashed_v_load_3_reg_1636 <= squashed_v_q12;
        squashed_v_load_4_reg_1641 <= squashed_v_q11;
        weighted_input_u_3_load_reg_1671 <= weighted_input_u_3_q1;
        weighted_input_u_4_load_reg_1676 <= weighted_input_u_4_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        squashed_v_load_5_reg_1701 <= squashed_v_q10;
        squashed_v_load_6_reg_1706 <= squashed_v_q9;
        weighted_input_u_5_load_reg_1746 <= weighted_input_u_5_q1;
        weighted_input_u_6_load_reg_1751 <= weighted_input_u_6_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        squashed_v_load_7_reg_1787 <= squashed_v_q8;
        squashed_v_load_8_reg_1792 <= squashed_v_q7;
        weighted_input_u_7_load_reg_1832 <= weighted_input_u_7_q1;
        weighted_input_u_load_1_reg_1837 <= weighted_input_u_q0;
    end
end

always @ (*) begin
    if (((icmp_ln286_fu_630_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter12_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten20_load = 14'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten20_load = indvar_flatten20_fu_138;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        output_agreement_ce0_local = 1'b1;
    end else begin
        output_agreement_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        output_agreement_we0_local = 1'b1;
    end else begin
        output_agreement_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        squashed_v_ce0_local = 1'b1;
    end else begin
        squashed_v_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        squashed_v_ce10_local = 1'b1;
    end else begin
        squashed_v_ce10_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        squashed_v_ce11_local = 1'b1;
    end else begin
        squashed_v_ce11_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        squashed_v_ce12_local = 1'b1;
    end else begin
        squashed_v_ce12_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        squashed_v_ce13_local = 1'b1;
    end else begin
        squashed_v_ce13_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        squashed_v_ce14_local = 1'b1;
    end else begin
        squashed_v_ce14_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        squashed_v_ce15_local = 1'b1;
    end else begin
        squashed_v_ce15_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        squashed_v_ce1_local = 1'b1;
    end else begin
        squashed_v_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        squashed_v_ce2_local = 1'b1;
    end else begin
        squashed_v_ce2_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        squashed_v_ce3_local = 1'b1;
    end else begin
        squashed_v_ce3_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        squashed_v_ce4_local = 1'b1;
    end else begin
        squashed_v_ce4_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        squashed_v_ce5_local = 1'b1;
    end else begin
        squashed_v_ce5_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        squashed_v_ce6_local = 1'b1;
    end else begin
        squashed_v_ce6_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        squashed_v_ce7_local = 1'b1;
    end else begin
        squashed_v_ce7_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        squashed_v_ce8_local = 1'b1;
    end else begin
        squashed_v_ce8_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        squashed_v_ce9_local = 1'b1;
    end else begin
        squashed_v_ce9_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        weighted_input_u_1_ce0_local = 1'b1;
    end else begin
        weighted_input_u_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        weighted_input_u_1_ce1_local = 1'b1;
    end else begin
        weighted_input_u_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        weighted_input_u_2_ce0_local = 1'b1;
    end else begin
        weighted_input_u_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        weighted_input_u_2_ce1_local = 1'b1;
    end else begin
        weighted_input_u_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        weighted_input_u_3_ce0_local = 1'b1;
    end else begin
        weighted_input_u_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        weighted_input_u_3_ce1_local = 1'b1;
    end else begin
        weighted_input_u_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        weighted_input_u_4_ce0_local = 1'b1;
    end else begin
        weighted_input_u_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        weighted_input_u_4_ce1_local = 1'b1;
    end else begin
        weighted_input_u_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        weighted_input_u_5_ce0_local = 1'b1;
    end else begin
        weighted_input_u_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        weighted_input_u_5_ce1_local = 1'b1;
    end else begin
        weighted_input_u_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        weighted_input_u_6_ce0_local = 1'b1;
    end else begin
        weighted_input_u_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        weighted_input_u_6_ce1_local = 1'b1;
    end else begin
        weighted_input_u_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        weighted_input_u_7_ce0_local = 1'b1;
    end else begin
        weighted_input_u_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        weighted_input_u_7_ce1_local = 1'b1;
    end else begin
        weighted_input_u_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        weighted_input_u_ce0_local = 1'b1;
    end else begin
        weighted_input_u_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        weighted_input_u_ce1_local = 1'b1;
    end else begin
        weighted_input_u_ce1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln286_1_fu_667_p2 = (i_1_fu_134 + 4'd1);

assign add_ln286_fu_636_p2 = (ap_sig_allocacmp_indvar_flatten20_load + 14'd1);

assign add_ln289_fu_681_p2 = (select_ln286_fu_659_p3 + 11'd1);

assign add_ln294_10_fu_1358_p2 = (shl_ln294_s_fu_1351_p3 + mul_ln294_11_reg_2087);

assign add_ln294_11_fu_1381_p2 = (shl_ln294_10_fu_1373_p3 + mul_ln294_12_reg_2097);

assign add_ln294_12_fu_1407_p2 = (shl_ln294_11_fu_1400_p3 + mul_ln294_13_reg_2122);

assign add_ln294_13_fu_1430_p2 = (shl_ln294_12_fu_1422_p3 + mul_ln294_14_reg_2132);

assign add_ln294_14_fu_1452_p2 = (shl_ln294_13_fu_1445_p3 + mul_ln294_15_reg_2142);

assign add_ln294_1_fu_987_p2 = (shl_ln294_1_fu_979_p3 + mul_ln294_2_reg_1731);

assign add_ln294_2_fu_1049_p2 = (shl_ln294_2_fu_1042_p3 + mul_ln294_3_reg_1807);

assign add_ln294_3_fu_1072_p2 = (shl_ln294_3_fu_1064_p3 + mul_ln294_4_reg_1817);

assign add_ln294_4_fu_1134_p2 = (shl_ln294_4_fu_1127_p3 + mul_ln294_5_reg_1882);

assign add_ln294_5_fu_1157_p2 = (shl_ln294_5_fu_1149_p3 + mul_ln294_6_reg_1892);

assign add_ln294_6_fu_1234_p2 = (shl_ln294_6_fu_1227_p3 + mul_ln294_7_reg_1957);

assign add_ln294_7_fu_1257_p2 = (shl_ln294_7_fu_1249_p3 + mul_ln294_8_reg_1967);

assign add_ln294_8_fu_1301_p2 = (shl_ln294_8_fu_1294_p3 + mul_ln294_9_reg_2027);

assign add_ln294_9_fu_1324_p2 = (shl_ln294_9_fu_1316_p3 + mul_ln294_10_reg_2037);

assign add_ln294_fu_964_p2 = (shl_ln2_fu_957_p3 + mul_ln294_1_reg_1721);

assign add_ln296_fu_1280_p2 = (zext_ln289_fu_1224_p1 + empty_fu_1198_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_fu_1198_p2 = (p_shl1_fu_1180_p3 + p_shl33_fu_1194_p1);

assign grp_fu_531_p_ce = 1'b1;

assign grp_fu_531_p_din0 = sext_ln294_fu_851_p1;

assign grp_fu_531_p_din1 = squashed_v_load_1_cast_fu_815_p1;

assign grp_fu_535_p_ce = 1'b1;

assign grp_fu_535_p_din0 = sext_ln294_1_fu_855_p1;

assign grp_fu_535_p_din1 = squashed_v_load_2_cast_fu_819_p1;

assign grp_fu_539_p_ce = 1'b1;

assign grp_fu_539_p_din0 = sext_ln294_2_fu_859_p1;

assign grp_fu_539_p_din1 = squashed_v_load_3_cast_fu_823_p1;

assign grp_fu_543_p_ce = 1'b1;

assign grp_fu_543_p_din0 = sext_ln294_3_fu_905_p1;

assign grp_fu_543_p_din1 = squashed_v_load_4_cast_fu_863_p1;

assign grp_fu_547_p_ce = 1'b1;

assign grp_fu_547_p_din0 = sext_ln294_4_fu_909_p1;

assign grp_fu_547_p_din1 = squashed_v_load_5_cast_fu_867_p1;

assign grp_fu_551_p_ce = 1'b1;

assign grp_fu_551_p_din0 = sext_ln294_5_fu_1002_p1;

assign grp_fu_551_p_din1 = squashed_v_load_6_cast_fu_925_p1;

assign grp_fu_555_p_ce = 1'b1;

assign grp_fu_555_p_din0 = sext_ln294_6_fu_1006_p1;

assign grp_fu_555_p_din1 = squashed_v_load_7_cast_fu_929_p1;

assign grp_fu_559_p_ce = 1'b1;

assign grp_fu_559_p_din0 = sext_ln294_7_fu_1087_p1;

assign grp_fu_559_p_din1 = squashed_v_load_8_cast_fu_1010_p1;

assign grp_fu_563_p_ce = 1'b1;

assign grp_fu_563_p_din0 = sext_ln294_8_fu_1091_p1;

assign grp_fu_563_p_din1 = squashed_v_load_9_cast_fu_1014_p1;

assign grp_fu_567_p_ce = 1'b1;

assign grp_fu_567_p_din0 = sext_ln294_9_fu_1172_p1;

assign grp_fu_567_p_din1 = squashed_v_load_10_cast_fu_1095_p1;

assign grp_fu_571_p_ce = 1'b1;

assign grp_fu_571_p_din0 = sext_ln294_10_fu_1176_p1;

assign grp_fu_571_p_din1 = squashed_v_load_11_cast_fu_1099_p1;

assign grp_fu_575_p_ce = 1'b1;

assign grp_fu_575_p_din0 = sext_ln294_11_fu_1272_p1;

assign grp_fu_575_p_din1 = squashed_v_load_12_cast_fu_1204_p1;

assign grp_fu_579_p_ce = 1'b1;

assign grp_fu_579_p_din0 = sext_ln294_12_fu_1276_p1;

assign grp_fu_579_p_din1 = squashed_v_load_13_cast_fu_1208_p1;

assign grp_fu_583_p_ce = 1'b1;

assign grp_fu_583_p_din0 = sext_ln294_13_fu_1339_p1;

assign grp_fu_583_p_din1 = squashed_v_load_14_cast_fu_1286_p1;

assign grp_fu_587_p_ce = 1'b1;

assign grp_fu_587_p_din0 = sext_ln294_14_fu_1343_p1;

assign grp_fu_587_p_din1 = squashed_v_load_15_cast_fu_1290_p1;

assign grp_fu_591_p_ce = 1'b1;

assign grp_fu_591_p_din0 = sext_ln294_15_fu_1396_p1;

assign grp_fu_591_p_din1 = sext_ln289_fu_1347_p1;

assign icmp_ln286_fu_630_p2 = ((ap_sig_allocacmp_indvar_flatten20_load == 14'd11520) ? 1'b1 : 1'b0);

assign icmp_ln289_fu_653_p2 = ((j_fu_130 == 11'd1152) ? 1'b1 : 1'b0);

assign or_ln_fu_913_p3 = {{tmp_39_reg_1566_pp0_iter4_reg}, {1'd1}};

assign output_agreement_address0 = zext_ln296_fu_1468_p1;

assign output_agreement_ce0 = output_agreement_ce0_local;

assign output_agreement_d0 = {{add_ln294_14_fu_1452_p2[47:16]}};

assign output_agreement_we0 = output_agreement_we0_local;

assign p_cast15_fu_704_p1 = tmp_16_fu_697_p3;

assign p_cast16_fu_740_p1 = tmp_17_fu_733_p3;

assign p_cast17_fu_752_p1 = tmp_18_fu_745_p3;

assign p_cast18_fu_798_p1 = tmp_19_fu_791_p3;

assign p_cast19_fu_810_p1 = tmp_20_fu_803_p3;

assign p_cast20_fu_834_p1 = tmp_21_fu_827_p3;

assign p_cast21_fu_846_p1 = tmp_22_fu_839_p3;

assign p_cast22_fu_878_p1 = tmp_23_fu_871_p3;

assign p_cast23_fu_890_p1 = tmp_24_fu_883_p3;

assign p_cast24_fu_940_p1 = tmp_25_fu_933_p3;

assign p_cast25_fu_952_p1 = tmp_26_fu_945_p3;

assign p_cast26_fu_1025_p1 = tmp_27_fu_1018_p3;

assign p_cast27_fu_1037_p1 = tmp_28_fu_1030_p3;

assign p_cast28_fu_1110_p1 = tmp_29_fu_1103_p3;

assign p_cast29_fu_1122_p1 = tmp_30_fu_1115_p3;

assign p_cast30_fu_1219_p1 = tmp_31_fu_1212_p3;

assign p_shl1_fu_1180_p3 = {{select_ln286_1_reg_1503_pp0_iter8_reg}, {10'd0}};

assign p_shl31_fu_723_p1 = tmp_115_fu_716_p3;

assign p_shl33_fu_1194_p1 = tmp_fu_1187_p3;

assign p_shl_fu_709_p3 = {{select_ln286_1_reg_1503}, {11'd0}};

assign p_udiv2428_fu_727_p2 = (p_shl_fu_709_p3 + p_shl31_fu_723_p1);

assign p_udiv2527_cast_fu_764_p1 = p_udiv_fu_757_p3;

assign p_udiv26_fu_768_p2 = (p_udiv2527_cast_fu_764_p1 + p_udiv2428_fu_727_p2);

assign p_udiv_fu_757_p3 = {{select_ln286_reg_1497}, {1'd0}};

assign select_ln286_1_fu_673_p3 = ((icmp_ln289_fu_653_p2[0:0] == 1'b1) ? add_ln286_1_fu_667_p2 : i_1_fu_134);

assign select_ln286_fu_659_p3 = ((icmp_ln289_fu_653_p2[0:0] == 1'b1) ? 11'd0 : j_fu_130);

assign sext_ln289_fu_1347_p1 = $signed(squashed_v_load_15_reg_2082);

assign sext_ln294_10_fu_1176_p1 = $signed(weighted_input_u_2_load_1_reg_1912);

assign sext_ln294_11_fu_1272_p1 = $signed(weighted_input_u_3_load_1_reg_1982);

assign sext_ln294_12_fu_1276_p1 = $signed(weighted_input_u_4_load_1_reg_1987);

assign sext_ln294_13_fu_1339_p1 = $signed(weighted_input_u_5_load_1_reg_2052);

assign sext_ln294_14_fu_1343_p1 = $signed(weighted_input_u_6_load_1_reg_2057);

assign sext_ln294_15_fu_1396_p1 = $signed(weighted_input_u_7_load_1_reg_2112);

assign sext_ln294_1_fu_855_p1 = $signed(weighted_input_u_1_load_reg_1601);

assign sext_ln294_2_fu_859_p1 = $signed(weighted_input_u_2_load_reg_1606);

assign sext_ln294_3_fu_905_p1 = $signed(weighted_input_u_3_load_reg_1671);

assign sext_ln294_4_fu_909_p1 = $signed(weighted_input_u_4_load_reg_1676);

assign sext_ln294_5_fu_1002_p1 = $signed(weighted_input_u_5_load_reg_1746);

assign sext_ln294_6_fu_1006_p1 = $signed(weighted_input_u_6_load_reg_1751);

assign sext_ln294_7_fu_1087_p1 = $signed(weighted_input_u_7_load_reg_1832);

assign sext_ln294_8_fu_1091_p1 = $signed(weighted_input_u_load_1_reg_1837);

assign sext_ln294_9_fu_1172_p1 = $signed(weighted_input_u_1_load_1_reg_1907);

assign sext_ln294_fu_851_p1 = $signed(weighted_input_u_load_reg_1596);

assign shl_ln294_10_fu_1373_p3 = {{tmp_44_fu_1363_p4}, {16'd0}};

assign shl_ln294_11_fu_1400_p3 = {{tmp_45_reg_2127}, {16'd0}};

assign shl_ln294_12_fu_1422_p3 = {{tmp_46_fu_1412_p4}, {16'd0}};

assign shl_ln294_13_fu_1445_p3 = {{tmp_47_reg_2147}, {16'd0}};

assign shl_ln294_1_fu_979_p3 = {{tmp_33_fu_969_p4}, {16'd0}};

assign shl_ln294_2_fu_1042_p3 = {{tmp_34_reg_1812}, {16'd0}};

assign shl_ln294_3_fu_1064_p3 = {{tmp_35_fu_1054_p4}, {16'd0}};

assign shl_ln294_4_fu_1127_p3 = {{tmp_36_reg_1887}, {16'd0}};

assign shl_ln294_5_fu_1149_p3 = {{tmp_37_fu_1139_p4}, {16'd0}};

assign shl_ln294_6_fu_1227_p3 = {{tmp_38_reg_1962}, {16'd0}};

assign shl_ln294_7_fu_1249_p3 = {{tmp_40_fu_1239_p4}, {16'd0}};

assign shl_ln294_8_fu_1294_p3 = {{tmp_41_reg_2032}, {16'd0}};

assign shl_ln294_9_fu_1316_p3 = {{tmp_42_fu_1306_p4}, {16'd0}};

assign shl_ln294_s_fu_1351_p3 = {{tmp_43_reg_2092}, {16'd0}};

assign shl_ln2_fu_957_p3 = {{tmp_32_reg_1726}, {16'd0}};

assign squashed_v_address0 = p_cast30_fu_1219_p1;

assign squashed_v_address1 = p_cast29_fu_1122_p1;

assign squashed_v_address10 = p_cast20_fu_834_p1;

assign squashed_v_address11 = p_cast19_fu_810_p1;

assign squashed_v_address12 = p_cast18_fu_798_p1;

assign squashed_v_address13 = p_cast17_fu_752_p1;

assign squashed_v_address14 = p_cast16_fu_740_p1;

assign squashed_v_address15 = p_cast15_fu_704_p1;

assign squashed_v_address2 = p_cast28_fu_1110_p1;

assign squashed_v_address3 = p_cast27_fu_1037_p1;

assign squashed_v_address4 = p_cast26_fu_1025_p1;

assign squashed_v_address5 = p_cast25_fu_952_p1;

assign squashed_v_address6 = p_cast24_fu_940_p1;

assign squashed_v_address7 = p_cast23_fu_890_p1;

assign squashed_v_address8 = p_cast22_fu_878_p1;

assign squashed_v_address9 = p_cast21_fu_846_p1;

assign squashed_v_ce0 = squashed_v_ce0_local;

assign squashed_v_ce1 = squashed_v_ce1_local;

assign squashed_v_ce10 = squashed_v_ce10_local;

assign squashed_v_ce11 = squashed_v_ce11_local;

assign squashed_v_ce12 = squashed_v_ce12_local;

assign squashed_v_ce13 = squashed_v_ce13_local;

assign squashed_v_ce14 = squashed_v_ce14_local;

assign squashed_v_ce15 = squashed_v_ce15_local;

assign squashed_v_ce2 = squashed_v_ce2_local;

assign squashed_v_ce3 = squashed_v_ce3_local;

assign squashed_v_ce4 = squashed_v_ce4_local;

assign squashed_v_ce5 = squashed_v_ce5_local;

assign squashed_v_ce6 = squashed_v_ce6_local;

assign squashed_v_ce7 = squashed_v_ce7_local;

assign squashed_v_ce8 = squashed_v_ce8_local;

assign squashed_v_ce9 = squashed_v_ce9_local;

assign squashed_v_load_10_cast_fu_1095_p1 = $signed(squashed_v_load_9_reg_1862);

assign squashed_v_load_11_cast_fu_1099_p1 = $signed(squashed_v_load_10_reg_1867);

assign squashed_v_load_12_cast_fu_1204_p1 = $signed(squashed_v_load_11_reg_1937);

assign squashed_v_load_13_cast_fu_1208_p1 = $signed(squashed_v_load_12_reg_1942);

assign squashed_v_load_14_cast_fu_1286_p1 = $signed(squashed_v_load_13_reg_2012);

assign squashed_v_load_15_cast_fu_1290_p1 = $signed(squashed_v_load_14_reg_2017);

assign squashed_v_load_1_cast_fu_815_p1 = $signed(squashed_v_load_reg_1571);

assign squashed_v_load_2_cast_fu_819_p1 = $signed(squashed_v_load_1_reg_1576);

assign squashed_v_load_3_cast_fu_823_p1 = $signed(squashed_v_load_2_reg_1581);

assign squashed_v_load_4_cast_fu_863_p1 = $signed(squashed_v_load_3_reg_1636);

assign squashed_v_load_5_cast_fu_867_p1 = $signed(squashed_v_load_4_reg_1641);

assign squashed_v_load_6_cast_fu_925_p1 = $signed(squashed_v_load_5_reg_1701);

assign squashed_v_load_7_cast_fu_929_p1 = $signed(squashed_v_load_6_reg_1706);

assign squashed_v_load_8_cast_fu_1010_p1 = $signed(squashed_v_load_7_reg_1787);

assign squashed_v_load_9_cast_fu_1014_p1 = $signed(squashed_v_load_8_reg_1792);

assign tmp_115_fu_716_p3 = {{select_ln286_1_reg_1503}, {8'd0}};

assign tmp_16_fu_697_p3 = {{select_ln286_1_reg_1503}, {4'd0}};

assign tmp_17_fu_733_p3 = {{select_ln286_1_reg_1503}, {4'd1}};

assign tmp_18_fu_745_p3 = {{select_ln286_1_reg_1503}, {4'd2}};

assign tmp_19_fu_791_p3 = {{select_ln286_1_reg_1503_pp0_iter2_reg}, {4'd3}};

assign tmp_20_fu_803_p3 = {{select_ln286_1_reg_1503_pp0_iter2_reg}, {4'd4}};

assign tmp_21_fu_827_p3 = {{select_ln286_1_reg_1503_pp0_iter3_reg}, {4'd5}};

assign tmp_22_fu_839_p3 = {{select_ln286_1_reg_1503_pp0_iter3_reg}, {4'd6}};

assign tmp_23_fu_871_p3 = {{select_ln286_1_reg_1503_pp0_iter4_reg}, {4'd7}};

assign tmp_24_fu_883_p3 = {{select_ln286_1_reg_1503_pp0_iter4_reg}, {4'd8}};

assign tmp_25_fu_933_p3 = {{select_ln286_1_reg_1503_pp0_iter5_reg}, {4'd9}};

assign tmp_26_fu_945_p3 = {{select_ln286_1_reg_1503_pp0_iter5_reg}, {4'd10}};

assign tmp_27_fu_1018_p3 = {{select_ln286_1_reg_1503_pp0_iter6_reg}, {4'd11}};

assign tmp_28_fu_1030_p3 = {{select_ln286_1_reg_1503_pp0_iter6_reg}, {4'd12}};

assign tmp_29_fu_1103_p3 = {{select_ln286_1_reg_1503_pp0_iter7_reg}, {4'd13}};

assign tmp_30_fu_1115_p3 = {{select_ln286_1_reg_1503_pp0_iter7_reg}, {4'd14}};

assign tmp_31_fu_1212_p3 = {{select_ln286_1_reg_1503_pp0_iter8_reg}, {4'd15}};

assign tmp_33_fu_969_p4 = {{add_ln294_fu_964_p2[47:16]}};

assign tmp_35_fu_1054_p4 = {{add_ln294_2_fu_1049_p2[47:16]}};

assign tmp_37_fu_1139_p4 = {{add_ln294_4_fu_1134_p2[47:16]}};

assign tmp_40_fu_1239_p4 = {{add_ln294_6_fu_1234_p2[47:16]}};

assign tmp_42_fu_1306_p4 = {{add_ln294_8_fu_1301_p2[47:16]}};

assign tmp_44_fu_1363_p4 = {{add_ln294_10_fu_1358_p2[47:16]}};

assign tmp_46_fu_1412_p4 = {{add_ln294_12_fu_1407_p2[47:16]}};

assign tmp_fu_1187_p3 = {{select_ln286_1_reg_1503_pp0_iter8_reg}, {7'd0}};

assign weighted_input_u_1_address0 = zext_ln294_1_reg_1761;

assign weighted_input_u_1_address1 = zext_ln294_fu_774_p1;

assign weighted_input_u_1_ce0 = weighted_input_u_1_ce0_local;

assign weighted_input_u_1_ce1 = weighted_input_u_1_ce1_local;

assign weighted_input_u_2_address0 = zext_ln294_1_reg_1761;

assign weighted_input_u_2_address1 = zext_ln294_fu_774_p1;

assign weighted_input_u_2_ce0 = weighted_input_u_2_ce0_local;

assign weighted_input_u_2_ce1 = weighted_input_u_2_ce1_local;

assign weighted_input_u_3_address0 = zext_ln294_1_reg_1761_pp0_iter6_reg;

assign weighted_input_u_3_address1 = zext_ln294_reg_1542;

assign weighted_input_u_3_ce0 = weighted_input_u_3_ce0_local;

assign weighted_input_u_3_ce1 = weighted_input_u_3_ce1_local;

assign weighted_input_u_4_address0 = zext_ln294_1_reg_1761_pp0_iter6_reg;

assign weighted_input_u_4_address1 = zext_ln294_reg_1542;

assign weighted_input_u_4_ce0 = weighted_input_u_4_ce0_local;

assign weighted_input_u_4_ce1 = weighted_input_u_4_ce1_local;

assign weighted_input_u_5_address0 = zext_ln294_1_reg_1761_pp0_iter7_reg;

assign weighted_input_u_5_address1 = zext_ln294_reg_1542_pp0_iter3_reg;

assign weighted_input_u_5_ce0 = weighted_input_u_5_ce0_local;

assign weighted_input_u_5_ce1 = weighted_input_u_5_ce1_local;

assign weighted_input_u_6_address0 = zext_ln294_1_reg_1761_pp0_iter7_reg;

assign weighted_input_u_6_address1 = zext_ln294_reg_1542_pp0_iter3_reg;

assign weighted_input_u_6_ce0 = weighted_input_u_6_ce0_local;

assign weighted_input_u_6_ce1 = weighted_input_u_6_ce1_local;

assign weighted_input_u_7_address0 = zext_ln294_1_reg_1761_pp0_iter8_reg;

assign weighted_input_u_7_address1 = zext_ln294_reg_1542_pp0_iter4_reg;

assign weighted_input_u_7_ce0 = weighted_input_u_7_ce0_local;

assign weighted_input_u_7_ce1 = weighted_input_u_7_ce1_local;

assign weighted_input_u_address0 = zext_ln294_1_fu_920_p1;

assign weighted_input_u_address1 = zext_ln294_fu_774_p1;

assign weighted_input_u_ce0 = weighted_input_u_ce0_local;

assign weighted_input_u_ce1 = weighted_input_u_ce1_local;

assign zext_ln289_fu_1224_p1 = select_ln286_reg_1497_pp0_iter8_reg;

assign zext_ln294_1_fu_920_p1 = or_ln_fu_913_p3;

assign zext_ln294_fu_774_p1 = p_udiv26_fu_768_p2;

assign zext_ln296_fu_1468_p1 = add_ln296_reg_2067_pp0_iter12_reg;

always @ (posedge ap_clk) begin
    zext_ln294_reg_1542[0] <= 1'b0;
    zext_ln294_reg_1542[63:15] <= 49'b0000000000000000000000000000000000000000000000000;
    zext_ln294_reg_1542_pp0_iter3_reg[0] <= 1'b0;
    zext_ln294_reg_1542_pp0_iter3_reg[63:15] <= 49'b0000000000000000000000000000000000000000000000000;
    zext_ln294_reg_1542_pp0_iter4_reg[0] <= 1'b0;
    zext_ln294_reg_1542_pp0_iter4_reg[63:15] <= 49'b0000000000000000000000000000000000000000000000000;
    zext_ln294_1_reg_1761[0] <= 1'b1;
    zext_ln294_1_reg_1761[63:15] <= 49'b0000000000000000000000000000000000000000000000000;
    zext_ln294_1_reg_1761_pp0_iter6_reg[0] <= 1'b1;
    zext_ln294_1_reg_1761_pp0_iter6_reg[63:15] <= 49'b0000000000000000000000000000000000000000000000000;
    zext_ln294_1_reg_1761_pp0_iter7_reg[0] <= 1'b1;
    zext_ln294_1_reg_1761_pp0_iter7_reg[63:15] <= 49'b0000000000000000000000000000000000000000000000000;
    zext_ln294_1_reg_1761_pp0_iter8_reg[0] <= 1'b1;
    zext_ln294_1_reg_1761_pp0_iter8_reg[63:15] <= 49'b0000000000000000000000000000000000000000000000000;
end

endmodule //digitcaps_accel_digitcaps_accel_Pipeline_VITIS_LOOP_286_1_VITIS_LOOP_289_2
