# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/beta/P4P-CapsuleNetworkAccelerator/accel/app/CapsuleNetwork/build_flow/DPUCZDX8G_zcu102/binary_container_1/link/vivado/vpl/output/vitis_design_ooc_copy.xdc

# Block Designs: bd/vitis_design/vitis_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design || ORIG_REF_NAME==vitis_design} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_axi_intc_0_0/vitis_design_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_axi_intc_0_0 || ORIG_REF_NAME==vitis_design_axi_intc_0_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_axi_interconnect_lpd_0/vitis_design_axi_interconnect_lpd_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_axi_interconnect_lpd_0 || ORIG_REF_NAME==vitis_design_axi_interconnect_lpd_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_axi_register_slice_0_0/vitis_design_axi_register_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_axi_register_slice_0_0 || ORIG_REF_NAME==vitis_design_axi_register_slice_0_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_axi_vip_0_0/vitis_design_axi_vip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_axi_vip_0_0 || ORIG_REF_NAME==vitis_design_axi_vip_0_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_axi_vip_1_0/vitis_design_axi_vip_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_axi_vip_1_0 || ORIG_REF_NAME==vitis_design_axi_vip_1_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_clk_wiz_0_0/vitis_design_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_clk_wiz_0_0 || ORIG_REF_NAME==vitis_design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_interconnect_axifull_0/vitis_design_interconnect_axifull_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_interconnect_axifull_0 || ORIG_REF_NAME==vitis_design_interconnect_axifull_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_interconnect_axihpm0fpd_0/vitis_design_interconnect_axihpm0fpd_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_interconnect_axihpm0fpd_0 || ORIG_REF_NAME==vitis_design_interconnect_axihpm0fpd_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_interconnect_axilite_0/vitis_design_interconnect_axilite_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_interconnect_axilite_0 || ORIG_REF_NAME==vitis_design_interconnect_axilite_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_proc_sys_reset_0_0/vitis_design_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_proc_sys_reset_0_0 || ORIG_REF_NAME==vitis_design_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_proc_sys_reset_1_0/vitis_design_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_proc_sys_reset_1_0 || ORIG_REF_NAME==vitis_design_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_proc_sys_reset_2_0/vitis_design_proc_sys_reset_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_proc_sys_reset_2_0 || ORIG_REF_NAME==vitis_design_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_proc_sys_reset_3_0/vitis_design_proc_sys_reset_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_proc_sys_reset_3_0 || ORIG_REF_NAME==vitis_design_proc_sys_reset_3_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_proc_sys_reset_4_0/vitis_design_proc_sys_reset_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_proc_sys_reset_4_0 || ORIG_REF_NAME==vitis_design_proc_sys_reset_4_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_proc_sys_reset_5_0/vitis_design_proc_sys_reset_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_proc_sys_reset_5_0 || ORIG_REF_NAME==vitis_design_proc_sys_reset_5_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_proc_sys_reset_6_0/vitis_design_proc_sys_reset_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_proc_sys_reset_6_0 || ORIG_REF_NAME==vitis_design_proc_sys_reset_6_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_ps_e_0/vitis_design_ps_e_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_ps_e_0 || ORIG_REF_NAME==vitis_design_ps_e_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_DPUCZDX8G_1_0/vitis_design_DPUCZDX8G_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_DPUCZDX8G_1_0 || ORIG_REF_NAME==vitis_design_DPUCZDX8G_1_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_digitcaps_accel_1_0/vitis_design_digitcaps_accel_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_digitcaps_accel_1_0 || ORIG_REF_NAME==vitis_design_digitcaps_accel_1_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_axi_ic_ps_e_S_AXI_HPC0_FPD_0/vitis_design_axi_ic_ps_e_S_AXI_HPC0_FPD_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_axi_ic_ps_e_S_AXI_HPC0_FPD_0 || ORIG_REF_NAME==vitis_design_axi_ic_ps_e_S_AXI_HPC0_FPD_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_axi_ic_ps_e_S_AXI_HP0_FPD_0/vitis_design_axi_ic_ps_e_S_AXI_HP0_FPD_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_axi_ic_ps_e_S_AXI_HP0_FPD_0 || ORIG_REF_NAME==vitis_design_axi_ic_ps_e_S_AXI_HP0_FPD_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_axi_ic_ps_e_S_AXI_HP1_FPD_0/vitis_design_axi_ic_ps_e_S_AXI_HP1_FPD_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_axi_ic_ps_e_S_AXI_HP1_FPD_0 || ORIG_REF_NAME==vitis_design_axi_ic_ps_e_S_AXI_HP1_FPD_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_axi_intc_0_intr_1_interrupt_concat_0/vitis_design_axi_intc_0_intr_1_interrupt_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_axi_intc_0_intr_1_interrupt_concat_0 || ORIG_REF_NAME==vitis_design_axi_intc_0_intr_1_interrupt_concat_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_irq_const_tieoff_0/vitis_design_irq_const_tieoff_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_irq_const_tieoff_0 || ORIG_REF_NAME==vitis_design_irq_const_tieoff_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_axcache_0xe_0/vitis_design_axcache_0xe_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_axcache_0xe_0 || ORIG_REF_NAME==vitis_design_axcache_0xe_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_axprot_0x2_0/vitis_design_axprot_0x2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_axprot_0x2_0 || ORIG_REF_NAME==vitis_design_axprot_0x2_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_auto_us_0/vitis_design_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_auto_us_0 || ORIG_REF_NAME==vitis_design_auto_us_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_xbar_3/vitis_design_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_xbar_3 || ORIG_REF_NAME==vitis_design_xbar_3} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_auto_pc_0/vitis_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_auto_pc_0 || ORIG_REF_NAME==vitis_design_auto_pc_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_m01_regslice_0/vitis_design_m01_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_m01_regslice_0 || ORIG_REF_NAME==vitis_design_m01_regslice_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_auto_cc_0/vitis_design_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_auto_cc_0 || ORIG_REF_NAME==vitis_design_auto_cc_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_m02_regslice_0/vitis_design_m02_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_m02_regslice_0 || ORIG_REF_NAME==vitis_design_m02_regslice_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_auto_cc_1/vitis_design_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_auto_cc_1 || ORIG_REF_NAME==vitis_design_auto_cc_1} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_auto_us_1/vitis_design_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_auto_us_1 || ORIG_REF_NAME==vitis_design_auto_us_1} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_xbar_4/vitis_design_xbar_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_xbar_4 || ORIG_REF_NAME==vitis_design_xbar_4} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_s00_regslice_4/vitis_design_s00_regslice_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_s00_regslice_4 || ORIG_REF_NAME==vitis_design_s00_regslice_4} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_auto_us_df_0/vitis_design_auto_us_df_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_auto_us_df_0 || ORIG_REF_NAME==vitis_design_auto_us_df_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_s01_regslice_4/vitis_design_s01_regslice_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_s01_regslice_4 || ORIG_REF_NAME==vitis_design_s01_regslice_4} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_s01_data_fifo_4/vitis_design_s01_data_fifo_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_s01_data_fifo_4 || ORIG_REF_NAME==vitis_design_s01_data_fifo_4} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_s02_regslice_0/vitis_design_s02_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_s02_regslice_0 || ORIG_REF_NAME==vitis_design_s02_regslice_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_s02_data_fifo_0/vitis_design_s02_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_s02_data_fifo_0 || ORIG_REF_NAME==vitis_design_s02_data_fifo_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_m00_data_fifo_4/vitis_design_m00_data_fifo_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_m00_data_fifo_4 || ORIG_REF_NAME==vitis_design_m00_data_fifo_4} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_m00_regslice_4/vitis_design_m00_regslice_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_m00_regslice_4 || ORIG_REF_NAME==vitis_design_m00_regslice_4} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_auto_ds_0/vitis_design_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_auto_ds_0 || ORIG_REF_NAME==vitis_design_auto_ds_0} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_xbar_5/vitis_design_xbar_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_xbar_5 || ORIG_REF_NAME==vitis_design_xbar_5} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_s00_regslice_5/vitis_design_s00_regslice_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_s00_regslice_5 || ORIG_REF_NAME==vitis_design_s00_regslice_5} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_auto_us_df_1/vitis_design_auto_us_df_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_auto_us_df_1 || ORIG_REF_NAME==vitis_design_auto_us_df_1} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_s01_regslice_5/vitis_design_s01_regslice_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_s01_regslice_5 || ORIG_REF_NAME==vitis_design_s01_regslice_5} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_s01_data_fifo_5/vitis_design_s01_data_fifo_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_s01_data_fifo_5 || ORIG_REF_NAME==vitis_design_s01_data_fifo_5} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_m00_data_fifo_5/vitis_design_m00_data_fifo_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_m00_data_fifo_5 || ORIG_REF_NAME==vitis_design_m00_data_fifo_5} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_m00_regslice_5/vitis_design_m00_regslice_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_m00_regslice_5 || ORIG_REF_NAME==vitis_design_m00_regslice_5} -quiet] -quiet

# IP: bd/vitis_design/ip/vitis_design_auto_ds_1/vitis_design_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vitis_design_auto_ds_1 || ORIG_REF_NAME==vitis_design_auto_ds_1} -quiet] -quiet

# XDC: /home/beta/P4P-CapsuleNetworkAccelerator/accel/app/CapsuleNetwork/build_flow/DPUCZDX8G_zcu102/binary_container_1/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/vitis_design_ooc.xdc
